### ISSUE TITLE
single-vm: ciao-down: Unable to launch instances from ciao-cli

### ISSUE THREAD

**Issue by jorgevgut** [01org/ciao#1016]
Hi, 
I'm experiencing a bug when launching instances from the cli.
Steps on which the issue occurred.
1. setup vm with ciao-down
2. ciao-down connect
3. ./setup
After a while of doing regular work, I restarted the single vm (on the singlevm logged with ciao-down connect)
./cleanup.sh
./setup.sh

-- 
At this point I tried to add an instance.
ciao-cli instance add --workload=e35ed972-c46c-4aad-a1e7-ef103ae079a2 --instances=1
To which I get: Created new (pending) instance: 09f71cf7-ab4c-4d1e-9f04-d6d4056d16b6
But doing a ciao-cli instance list shows nothing.

I ran the ./verify.sh script to make sure the cluster whas ok and I got this message.

> root@singlevm:~/src/github.com/01org/ciao/testutil/singlevm# ./verify.sh 
Workload 1
        Name: Clear Cloud
        UUID:e35ed972-c46c-4aad-a1e7-ef103ae079a2
        Image UUID: 
        CPUs: 2
        Memory: 128 MB
Workload 2
        Name: Docker Debian latest
        UUID:ca957444-fa46-11e5-94f9-38607786d9ec
        Image UUID: fa7d86d8-fa46-11e5-8493-38607786d9ec
        CPUs: 2
        Memory: 128 MB
Workload 3
        Name: Docker Iperf
        UUID:ab68111c-03a6-11e6-87de-001320fb6e31
        Image UUID: b5e696b8-03a6-11e6-a424-001320fb6e31
        CPUs: 2
        Memory: 128 MB
Workload 4
        Name: Fedora 24 Cloud
        UUID:79034317-3beb-447e-987d-4e310a8cf410
        Image UUID: 
        CPUs: 2
        Memory: 128 MB
F0116 17:00:29.533562   13351 instance.go:531] ciao-cli FATAL: HTTP Error [500] for [POST https://singlevm:8774/v2.1/22b76df6f9a44777bee79fbc14d01dd1/servers]: {"error":{"code":500,"name":"Internal Server Error","message":"Unable to Launch Tenant CNCI"}}
null
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x983400, 0xc400000000, 0x104, 0x280)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x967080, 0xc400000003, 0xc4203b8180, 0x9416b3, 0xb, 0x213, 0x0)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x967080, 0xc400000003, 0x1, 0xc42013b790, 0x1, 0x1)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42013b790, 0x1, 0x1)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc4203a41a0, 0xc4, 0x0, 0x0, 0x0)
        /root/src/github.com/01org/ciao/ciao-cli/main.go:132 +0x126
main.(*instanceAddCommand).run(0xc420086d20, 0xc42000c0e0, 0x0, 0x0, 0xc42000c0e0, 0x0)
        /root/src/github.com/01org/ciao/ciao-cli/instance.go:531 +0x60d
main.(*command).run(0x9654e8, 0xc42000c0e0, 0x0, 0x0, 0xc42008ccd8, 0x0)
        /root/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x15b
main.main()
        /root/src/github.com/01org/ciao/ciao-cli/main.go:466 +0xf7
FATAL ERROR exiting:  Unable to launch VMs 255

Workaround:
- Tried logging out and ciao-down stop, and ciao-down start but didn't work, I'm using ciao-down delete and reseting the environment.

So far, this has happened only one in two days. I'll update later if I experience this issue again to determine frequency.

**Comment by rbradford** [comment]
I have seen this as a flaky bug before. I think that is is related to having two CNCIs: one for the usual csr user and one from the admin user if you change your CIAO_USERNAME to admin to let you create a workload.

This is not sufficient to trigger the problem though - I wonder if we're hitting memory pressure which makes that second CNCI launch fail or something else.

Whilst trying to reproduce i've successfully worked with two tenants in the SingleVM environment so there must be a 2nd factor that shows this up.

Did you look in the ciao-controller logs to identify any error messages about the launching of the CNCI?

**Comment by jorgevgut** [comment]
Hi @rbradford ,
Thanks for your reply, at the moment I didn't, however I just finished re-deploying ciao-down (ciao-down delete, and then ciao-down prepare) and continue to experience the same problem.

I first ran singlevm/setup.sh, then tried to ciao-cli instance add and failed as before.
Then I ran verify.sh which gives me these log. 

> root@singlevm:~/src/github.com/01org/ciao/testutil/singlevm# ./verify.sh 
Workload 1
        Name: Docker Iperf
        UUID:ab68111c-03a6-11e6-87de-001320fb6e31
        Image UUID: b5e696b8-03a6-11e6-a424-001320fb6e31
        CPUs: 2
        Memory: 128 MB
Workload 2
        Name: Fedora 24 Cloud
        UUID:79034317-3beb-447e-987d-4e310a8cf410
        Image UUID: 
        CPUs: 2
        Memory: 128 MB
Workload 3
        Name: Clear Cloud
        UUID:e35ed972-c46c-4aad-a1e7-ef103ae079a2
        Image UUID: 
        CPUs: 2
        Memory: 128 MB
Workload 4
        Name: Docker Debian latest
        UUID:ca957444-fa46-11e5-94f9-38607786d9ec
        Image UUID: fa7d86d8-fa46-11e5-8493-38607786d9ec
        CPUs: 2
        Memory: 128 MB
Created new (pending) instance: 0065f3ed-de05-490d-ac95-47d523826ccf
Created new (pending) instance: 8b24cb35-d5c6-4243-bbbc-cf5bdebf735c
Using default tag: latest
latest: Pulling from library/debian
75a822cd7888: Pull complete 
Digest: sha256:f7062cf040f67f0c26ff46b3b44fe036c29468a7e69d8170f37c57f2eec1261b
Status: Downloaded newer image for debian:latest
Created new (pending) instance: 8a1719c3-8cb2-4911-a4e0-90a0e8b7eee2
Created new (pending) instance: c1803aa2-ff62-4dda-b54d-31202c4e630e
Waiting for instance to boot
Waiting for instance to boot
Waiting for instance to boot
Waiting for instance to boot
Waiting for instance to boot                                                                                                          Waiting for instance to boot                                                                                                          Unable check ssh connectivity into VM  

As a note I haven't seen "Waiting for instance to boot" before.

I picked this from /var/lib/ciao/logs/controller/ciao-controller.ERROR
> root@singlevm:/var# cat lib/ciao/logs/controller/ciao-controller.ERROR 
Log file created at: 2017/01/16 17:42:39
Running on machine: singlevm
Binary: Built with gc go1.7.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0116 17:42:39.686166   26670 client.go:243] SSNTP Error: Could not connect to 198.51.100.1:8888 (dial tcp 198.51.100.1:8888: getsockopt: connection refused)
E0116 17:42:39.687342   26670 client.go:243] SSNTP Error: Could not connect to singlevm:8888 (dial tcp 127.0.0.1:8888: getsockopt: connection refused)
E0116 17:42:39.687587   26670 client.go:243] SSNTP Error: Could not connect to localhost:8888 (dial tcp 127.0.0.1:8888: getsockopt: connection refused)
E0116 17:42:39.687594   26670 client.go:248] SSNTP Error: All server URIs failed - retrying in 1 seconds
E0116 17:42:40.687928   26670 client.go:243] SSNTP Error: Could not connect to 198.51.100.1:8888 (dial tcp 198.51.100.1:8888: getsockopt: connection refused)
E0116 17:42:40.688042   26670 client.go:243] SSNTP Error: Could not connect to singlevm:8888 (dial tcp 127.0.0.1:8888: getsockopt: connection refused)
E0116 17:42:40.688155   26670 client.go:243] SSNTP Error: Could not connect to localhost:8888 (dial tcp 127.0.0.1:8888: getsockopt: connection refused)
E0116 17:42:40.688160   26670 client.go:248] SSNTP Error: All server URIs failed - retrying in 4 seconds

Finally I also got this log from the launcher:

> /var/lib/ciao/logs/launcher/ciao-launcher.singlevm.root.log.ERROR.20170116-174239.26658 

> Log file created at: 2017/01/16 17:42:39
Running on machine: singlevm
Binary: Built with gc go1.7.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0116 17:42:39.594737   26658 client.go:243] SSNTP Error: Could not connect to 198.51.100.1:8888 (dial tcp 198.51.100.1:8888: getsockopt: connection refused)
E0116 17:42:39.600023   26658 client.go:243] SSNTP Error: Could not connect to singlevm:8888 (dial tcp 127.0.0.1:8888: getsockopt: connection refused)
E0116 17:42:39.600442   26658 client.go:243] SSNTP Error: Could not connect to localhost:8888 (dial tcp 127.0.0.1:8888: getsockopt: connection refused)
E0116 17:42:39.600452   26658 client.go:248] SSNTP Error: All server URIs failed - retrying in 5 seconds
E0116 17:45:10.366718   26658 network.go:286] cn.CreateCnciVnic failed cncivnic error: enable link up device or resource busy
E0116 17:45:10.380751   26658 instance.go:119] Unable to start instance[network_failure]: cncivnic error: enable link up device or resource busy
E0116 17:49:04.538065   26658 network.go:276] cn.CreateVnic failed invalid vnic or configuration
E0116 17:49:04.538164   26658 instance.go:119] Unable to start instance[network_failure]: invalid vnic or configuration
E0116 17:49:04.678115   26658 network.go:276] cn.CreateVnic failed invalid vnic or configuration
E0116 17:49:04.678124   26658 instance.go:119] Unable to start instance[network_failure]: invalid vnic or configuration
E0116 17:49:43.640963   26658 network.go:276] cn.CreateVnic failed invalid vnic or configuration
E0116 17:49:43.640974   26658 instance.go:119] Unable to start instance[network_failure]: invalid vnic or configuration
E0116 17:50:03.952480   26658 docker.go:520] Unable to get stats from container: 8a1719c3-8cb2-4911-a4e0-90a0e8b7eee2: Error response from daemon: page not found
E0116 17:50:03.954044   26658 network.go:269] cn.CreateVnic failed invalid vnic or configuration
E0116 17:50:03.954052   26658 instance.go:119] Unable to start instance[network_failure]: invalid vnic or configuration
E0116 17:50:09.511715   26658 docker.go:520] Unable to get stats from container: c1803aa2-ff62-4dda-b54d-31202c4e630e: Error response from daemon: page not found
E0116 17:50:09.513369   26658 network.go:269] cn.CreateVnic failed invalid vnic or configuration
E0116 17:50:09.513377   26658 instance.go:119] Unable to start instance[network_failure]: invalid vnic or configuration

I guess I'll try rebooting my host now.
Does this makes any sense to you?

**Comment by jorgevgut** [comment]
Here's a funny thing.
Before trying rebooting the host.
I did a cleanup.sh, then setup.sh and verify.sh.
It worked now for some reason.

Something different from the last time is that between setup.sh and verify.sh I tried a ciao-cli instance add.
I wonder if that may somehow trigger the problem. I didn't need to change the username to "admin" for it work. I'll update if I find different behaviors.

**Comment by markdryan** [comment]
@jorgevgut Sometimes something goes wrong with setup.sh but the script doesn't actually error out.  You can see the warning printed to the screen with all the rest of the output but it's easy to spot.  Next time this happens, can you paste all the output you get from setup.sh?

**Comment by jorgevgut** [comment]
@markdryan I haven't experienced this issue again since, once I got it working last week it has remained good. Maybe we can close, for now and reopen if more people starts experiencing the problem again?

**Comment by markdryan** [comment]
Let's keep it open.  I saw it once on Friday.

**Comment by markdryan** [comment]
Okay, let's close it.  We can re-open it if it re-appears.
