### ISSUE TITLE
Launcher should auto delete instances that stop

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#1041]
Currently, when an instance exits, launcher reports this fact to controller via the STATS, but continues to maintain some local state for the instance.   This state can be used to restart the instance at a later stage.  However, going forward instances in the exited status will become homeless.  They'll exist in the ciao cluster and controller's databases.  Their volumes will still exist, but they won't be associated with any compute or network node.  Therefore, when instances stop they can be deleted completely from their old hosts.

Launcher would send controller a InstanceDeleted event so controller knows that the instance has been deleted.  Once the instance has exited it will no longer figure in launcher's STATS.

**Comment by markdryan** [comment]
@kaccardi I'm not sure what the implications for controller are here.  My idea was to simple send the InstanceDeleted event but then the handling of this event may need to change in controller.  Please feel free to suggest a different way of doing this.

Also, what do you think about removing the instance from STATS.  Conceptually, this makes sense but it might break controller.  We could send one last STATS for the instance with its state set to exited.

**Comment by markdryan** [comment]
@kaccardi Perhaps we could leave InstanceDeleted unchanged and send a new event instead, InstanceEvacuated, when an instance dies of its own accord.  If it helps, we could also keep SSNTP STOP.  Launcher would handle STOP exactly the same way as it handles DELETE with the one exception that it sends an InstanceEvacuated event.  Perhaps this is what you and @mcastelino suggested earlier and I failed to grasp at the time.

What I really want to achieve here is to remove all the code in launcher that manages persistent instance state so that when an instance dies it disappears from the compute node.   But I have no real objection to handling the SSNTP STOP, and even RESTART if needed, in launcher and mapping these to the code that handles DELETE and START.  I'd still be able to delete most of the code I was planning to remove.

Ideally, I think it would be best to remove these commands entirely as it would allow us to delete code in launcher, ssntp, tesutils, scheduler and payloads, but maybe we could postpone this to the next sprint.  Another option would be to get rid of STOP and RESTART and add a flag to delete to indicate which event should be sent back to controller.

Regarding stats we can definitely send one last STAT command, but long term we're going to need to handle the case where controller stops receiving stats for an instance it did not explicitly delete, see https://github.com/01org/ciao/issues/1038.  However, this is really the autofencing problem and is a task for a later sprint.

**Comment by mcastelino** [comment]
@markdryan that is what I meant. You treat them exactly the same, except the response message. So the code flow will be exactly the same.

**Comment by markdryan** [comment]
@mcastelino Okay, sorry for the confusion.  @kaccardi if you'd prefer keep STOP for this sprint that's fine for me.
