### ISSUE TITLE
ciao-down fails ssh connectivity tests

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#1064]
verify.sh fails with a fresh ciao-down image. Unclear as to why.

**Comment by mcastelino** [comment]
The network connectivity tests are failing. This can be even duplicated with the networking unit test cases 
https://github.com/01org/ciao/tree/master/networking/libsnnet#testing

The simplest test that fails is
sudo -E `which go` test --tags travis -v --short --run TestCNContainer_Connectivity

This seems to have happened after the kernel or the distribution got upgraded.

The unit test cases pass on ubuntu 14.04 running  4.4.0-59-generic

The unit test cases are pass

**Comment by mcastelino** [comment]
@tpepper @tpepper Root caused the issue to 
```
bridge-nf-call-arptables
bridge-nf-call-iptables
bridge-nf-call-ip6tables

```
being set to 1. Setting them to 0, at least gets things to work.

I need to figure out a proper fix to this.

**Comment by markdryan** [comment]
I spent some time looking at this this morning but I'm no closer to figuring out what has changed.  So far, all I've managed to confirm is that it's not related to the kernel version or to docker.

I have an old image I created a while back and the network tests still work inside this image, even with the latest version of the ciao code.  The other odd thing is that the contents of /proc/sys/net/bridge are identical in both VMs, the one that works and the one that doesn't.

**Comment by mcastelino** [comment]
@tpepper @markdryan @kaccardi Found the root cause for this
Recent docker added a new rule "default deny on forward"
https://github.com/docker/libnetwork/commit/a493ddb42f7ef9e0a224c90489015202fc7398d9
This breaks our code as even our bridged traffic is getting pushed through the iptables (br_filter).

It does this if **docker is the one that enabled ip forwarding** on the system.
Which I think is fair behavior as it does not want to punch a wide hole in the user's firewall.

So we need to ensure we turn on ip forwarding on the systems that host ciao.
Longer term we should consider adding appropriate allow rules for all the bridges we create in ciao.

**Comment by Beanking77** [comment]
Still got failed ssh test with fresh ciao-down prepare and ./setup and setting above them to 0.Are there any hints or tips? Please help.
```
bridge-nf-call-arptables
bridge-nf-call-iptables
bridge-nf-call-ip6tables
```
docker version:
```
# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by markdryan** [comment]
@Beanking77 I've just tried with the latest version of docker inside singleVM and the SSH connectivity tests are working okay for me.  I'll try again by creating a new VM, but this will take a little bit of time.

In the meantime, what do you see if you type

ifconfig ciao_br

from inside ciao-down after running setup.sh?

Also, what errors you actually see?

**Comment by markdryan** [comment]
I tried creating a clean VM with ciao-down prepare and re-ran verify.sh.  I'm not seeing any errors.

**Comment by Beanking77** [comment]
thanks for your quick reply:)
after I ran setup.sh and ran verify.sh, here's whole logs:
```
root@singlevm:~/go/src/github.com/01org/ciao/testutil/singlevm# . ~/local/demo.sh
root@singlevm:~/go/src/github.com/01org/ciao/testutil/singlevm# . ~/local/verify.sh
Created new (pending) instance: 61ea0c35-da6e-4fd5-90e2-4cc6a05f2891
Created new (pending) instance: 2703c484-1c29-4421-8080-097d673a2e1b
# UUID                                 Status  Private IP SSH IP SSH PORT
1 b1eb260f-4c23-4089-9c04-892bed49316f pending 172.16.0.2 N/A    N/A
2 61ea0c35-da6e-4fd5-90e2-4cc6a05f2891 pending 172.16.0.3 N/A N/A
3 2703c484-1c29-4421-8080-097d673a2e1b pending 172.16.0.5 N/A N/A
4 c947055c-e0d4-4c3d-92e3-412f4a0cbee3 pending 172.16.0.4 N/A N/A
Using default tag: latest
latest: Pulling from library/debian
Digest: sha256:72f784399fd2719b4cb4e16ef8e369a39dc67f53d978cd3e2e7bf4e502c7b793
Status: Image is up to date for debian:latest
Starting workload 5149ae0a-2371-48ab-be5b-39d765125369
Created new (pending) instance: b0a69871-fd0b-491a-a4f7-b56568bc15b8
# UUID                                 Status Private IP SSH IP        SSH PORT
1 b1eb260f-4c23-4089-9c04-892bed49316f active 172.16.0.2 198.51.100.82 33002
2 61ea0c35-da6e-4fd5-90e2-4cc6a05f2891 active 172.16.0.3 198.51.100.82 33003
3 2703c484-1c29-4421-8080-097d673a2e1b active 172.16.0.5 198.51.100.82 33005
4 c947055c-e0d4-4c3d-92e3-412f4a0cbee3 active 172.16.0.4 198.51.100.82 33004
5 b0a69871-fd0b-491a-a4f7-b56568bc15b8 active 172.16.0.6 198.51.100.82 33006
Created new (pending) instance: 39895771-9fb0-4c7b-9502-bad6c73c7f37
# UUID                                 Status Private IP SSH IP        SSH PORT
1 b1eb260f-4c23-4089-9c04-892bed49316f active 172.16.0.2 198.51.100.82 33002
2 61ea0c35-da6e-4fd5-90e2-4cc6a05f2891 active 172.16.0.3 198.51.100.82 33003
3 2703c484-1c29-4421-8080-097d673a2e1b active 172.16.0.5 198.51.100.82 33005
4 c947055c-e0d4-4c3d-92e3-412f4a0cbee3 active 172.16.0.4 198.51.100.82 33004
5 b0a69871-fd0b-491a-a4f7-b56568bc15b8 active 172.16.0.6 198.51.100.82 33006
6 39895771-9fb0-4c7b-9502-bad6c73c7f37 active 172.16.0.7 198.51.100.82 33007
# UUID                                 Status Private IP SSH IP        SSH PORT
1 b1eb260f-4c23-4089-9c04-892bed49316f active 172.16.0.2 198.51.100.82 33002
2 61ea0c35-da6e-4fd5-90e2-4cc6a05f2891 active 172.16.0.3 198.51.100.82 33003
3 2703c484-1c29-4421-8080-097d673a2e1b active 172.16.0.5 198.51.100.82 33005
4 c947055c-e0d4-4c3d-92e3-412f4a0cbee3 active 172.16.0.4 198.51.100.82 33004
5 b0a69871-fd0b-491a-a4f7-b56568bc15b8 active 172.16.0.6 198.51.100.82 33006
6 39895771-9fb0-4c7b-9502-bad6c73c7f37 active 172.16.0.7 198.51.100.82 33007
-bash: connect: No route to host
-bash: /dev/tcp/198.51.100.82/33002: No route to host
Attempting to ssh to: 198.51.100.82
Retrying ssh connection 1
-bash: connect: No route to host
-bash: /dev/tcp/198.51.100.82/33002: No route to host
Attempting to ssh to: 198.51.100.82
Retrying ssh connection 2
-bash: connect: No route to host
-bash: /dev/tcp/198.51.100.82/33002: No route to host
Attempting to ssh to: 198.51.100.82
Retrying ssh connection 3
-bash: connect: No route to host
-bash: /dev/tcp/198.51.100.82/33002: No route to host
Attempting to ssh to: 198.51.100.82
Retrying ssh connection 4
-bash: connect: No route to host
-bash: /dev/tcp/198.51.100.82/33002: No route to host
Attempting to ssh to: 198.51.100.82
Retrying ssh connection 5
-bash: connect: No route to host
-bash: /dev/tcp/198.51.100.82/33002: No route to host
Attempting to ssh to: 198.51.100.82
Retrying ssh connection 6
Unable check ssh connectivity into VM
```
and failed the ssh test.

here's ifconfig ciao_br:
```
root@singlevm:~/go/src/github.com/01org/ciao/testutil/singlevm# ifconfig ciao_br
ciao_br   Link encap:Ethernet  HWaddr 66:fb:ce:ac:85:93
          inet6 addr: fe80::64fb:ceff:feac:8593/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:1566 (1.5 KB)
```

**Comment by markdryan** [comment]
@mcastelino Any idea what might be going on here?  The fact that ciao_br exists means that your patch is present.

@Beanking77 What host OS are you using?

**Comment by Beanking77** [comment]
@markdryan I'm using Clear Linux 14260 with siglevm ubuntu 16.04.
