### ISSUE TITLE
singlevm: single machine mode fails with tls issues

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#1065]
You can no longer run testutil/singlevm/setup.sh directly on your dev machine (single machine mode) without ciao-down due to tls issues.

**Comment by kaccardi** [comment]
E0125 11:38:30.867236   94702 authenticate.go:43] ciao-cli ERROR: Could not get AuthenticatedClient Post https://<valid hostname deleted by me>:5000/v3/auth/tokens: tls: oversized record received with length 24932
E0125 11:38:30.869251   94702 identity.go:126] ciao-cli ERROR: Failed to create an AuthenticatedClient
E0125 11:38:30.872775   94702 main.go:235] ciao-cli ERROR: Could not send HTTP request Get https://<valid hostname deleted by me>:5000/v3/users//projects: tls: oversized record received with length 24932
F0125 11:38:30.872799   94702 main.go:429] ciao-cli FATAL: Get https://<valid hostname deleted by me>:5000/v3/users//projects: tls: oversized record received with length 24932

**Comment by kaccardi** [comment]
I removed the valid hostname from these urls manually - they previously did contain the correct hostname.

**Comment by tpepper** [comment]
In ```Get https://:5000/v3/users//projects``` should there be data between "users/" and "/projects"?

**Comment by tpepper** [comment]
Ignore that prior comment.  I believe it's a separate https://github.com/01org/ciao/issues/1068

**Comment by markdryan** [comment]
@kaccardi This should be fixed now.  Could you verify and close?
