### ISSUE TITLE
Ansible uses outdated version of ciao-cert causing deployment failures

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#1168]
I tried to install ciao via the ansible scripts this morning, and failed.  The reason for the failure seems to be that I have an old version of ciao-cert in /tmp/go/bin left over from an install I did last year.  This version is missing an option that the ansible scripts rely on and so the build fails.  I guess ansible should rebuild ciao-cert before using it.  Maybe a -u is missing go get is called.

```
TASK [ciao-controller : Create Scheduler key and CA certificate] ***************
fatal: [ciao-ctl.ld.intel.com]: FAILED! => {"changed": true, "cmd": ["/tmp/go/bin/ciao-cert", "-anchor", "-role", "scheduler", "-email=admin@example.com", "-organization=Example Inc.", "-ip=10.103.239.202", "-host=ciao-ctl.ld.intel.com", "-verify"], "delta": "0:00:00.012555", "end": "2017-02-17 10:17:59.746441", "failed": true, "rc": 2, "start": "2017-02-17 10:17:59.733886", "stderr": "flag provided but not defined: -anchor\nUsage of /tmp/go/bin/ciao-cert:\n  -alsologtostderr\n    \tlog to standard error as well as files\n  -directory string\n    \tInstallation directory (default \".\")\n  -dump string\n    \tPrint details about provided certificate\n  -elliptic-key\n    \tUse elliptic curve algorithms\n  -email string\n    \tCertificate email address (default \"ciao-devel@lists.clearlinux.org\")\n  -host string\n    \tComma-separated hostnames to generate a certificate for\n  -ip string\n    \tComma-separated IPs to generate a certificate for\n  -log_backtrace_at value\n    \twhen logging hits line file:N, emit a stack trace\n  -log_dir string\n    \tIf non-empty, write log files in this directory\n  -logtostderr\n    \tlog to standard error instead of files\n  -organization string\n    \tCertificates organization\n  -role value\n    \tComma separated list of SSNTP role [agent, scheduler, controller, netagent, server, cnciagent]\n  -server\n    \tWhether this cert should be a server one\n  -server-cert string\n    \tServer certificate for signing a client one\n  -stderrthreshold value\n    \tlogs at or above this threshold go to stderr\n  -v value\n    \tlog level for V logs\n  -verify\n    \tVerify client certificate\n  -vmodule value\n    \tcomma-separated list of pattern=N settings for file-filtered logging", "stdout": "", "stdout_lines": [], "warnings": []}
```

The workaround is to delete /tmp/go

**Comment by markdryan** [comment]
I ran cleanup and the directory was deleted.

Is it a requirement that you always run cleanup before installing?

**Comment by albertomurillo** [comment]
It is not required to run cleanup.yml before deploy.

The reason of not doing `-u` was to allow developer to make changes on the ciao directory and get those changes deployed.

What do you think on bringing `ciao_dev` option back to skip `-u` when `ciao_dev=True` and do the update when `ciao_dev=False` ?

**Comment by markdryan** [comment]
> It is not required to run cleanup.yml before deploy.

But what happens if the user makes some change to the cnci_agent.  If he just runs the playbook again will the cnci be rebuilt?

> What do you think on bringing ciao_dev option back to skip -u when ciao_dev=True and do the update when ciao_dev=False ?

That sounds good.  What does ciao_dev actually do?  Does it use your GOPATH rather than /tmp/go?

**Comment by markdryan** [comment]
> But what happens if the user makes some change to the cnci_agent. If he just runs the playbook again will the cnci be rebuilt?

I suppose what I'm trying to say is I think there are currently some cases where you do need to do a cleanup to before an install.  Maybe what we need to do is to simply identify these cases, treat them as bugs and fix them in the playbook.

**Comment by albertomurillo** [comment]
> But what happens if the user makes some change to the cnci_agent. If he just runs the playbook again will the cnci be rebuilt?

No, unless the user removes images/.cnci_ready and removes the image from ciao-image

> That sounds good. What does ciao_dev actually do? Does it use your GOPATH rather than /tmp/go?

Nothing, the option was removed when we switched to deploy from source code

**Comment by markdryan** [comment]
> Nothing, the option was removed when we switched to deploy from source code

What would it do if we brought it back?

> No, unless the user removes images/.cnci_ready and removes the image from ciao-image

And this is likely to cause a lot of confusion for people who are working on the cnci.  It would be great if we could identify all of these places where you currently do need to do a cleanup and fix them.
