### ISSUE TITLE
ansible installs ciao-cli on the network nodes

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#1170]
Is there a reason for this?

**Comment by albertomurillo** [comment]
To have ciao-cli available from any node in the cluster... If you think it is unnecessary I can remove it but I personally think it does no harm.

**Comment by markdryan** [comment]
@albertomurillo No that's fine.  This was really a question rather than a bug.  I'll switch the label and close it.  I just wanted to make sure that this was intended.
