### ISSUE TITLE
ansible deployed cluster does not work

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#1171]
The CNCI is unable to connect to the scheduler.  It seems to be a certificate issue.  Inside the CNCI I see

```
I0217 12:15:35.251166     294 client.go:225] SSNTP Info: 03f94fe0-e113-40c3-8962-16b5113b4d45 connecting to 10.103.239.202:8888
E0217 12:15:35.260294     294 client.go:243] SSNTP Error: Could not connect to 10.103.239.202:8888 (x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "serial:330668317042674988319618545653752732204"))
I0217 12:15:35.260342     294 client.go:225] SSNTP Info: 03f94fe0-e113-40c3-8962-16b5113b4d45 connecting to ciao-ctl.ld.intel.com:8888
E0217 12:15:35.275580     294 client.go:243] SSNTP Error: Could not connect to ciao-ctl.ld.intel.com:8888 (x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "serial:330668317042674988319618545653752732204"))
```

**Comment by markdryan** [comment]
Running cleanup and manually deleting all the rbd images and qemu instances allowed me to create a workable cluster but I'm not sure exactly which step fixed the image.  We're guessing that the problem occurred as the cnci image was not regenerated.

Our setup here is that we use multiple deployment machines to deploy to the same cluster.

**Comment by markdryan** [comment]
Could it be a problem with

- name: Remove local files

After I run cleanup the only directory that gets deleted is /tmp/go

        - ./openrc
        - ./admin-ciaorc
        - ./demo-ciaorc
        - ./clouds.yaml
        - ./certificates
        - ./images/.cnci_ready

are still present.

**Comment by albertomurillo** [comment]
So it didnt work as a combination of 3 factors...

- cleanup.yml not shutting down old vms https://github.com/01org/ciao/issues/1169
- cleanup.yml not deleting ceph volumes https://github.com/01org/ciao/issues/1172
- cleanup.yml not removing ./certificates or ./images/.cnci_ready

Ill track the latest in this issue
