### ISSUE TITLE
Ansible: Race condition in image upload

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#1181]
I did a cleanup and and tried to re-install my cluster.  The install failed with the following error:

```
TASK [ciao-controller : Upload "Clear Cloud"] **********************************
fatal: [ciao-ctl.ld.intel.com]: FAILED! => {"changed": true, "cmd": "/tmp/go/bin/ciao-cli image add --file images/clear-11960-cloud.img --name \"Clear Cloud\" --id df3768da-31f5-4ba6-82f0-127a1a705169", "delta": "0:00:00.261870", "end": "2017-02-20 09:37:15.844457", "failed": true, "rc": 255, "start": "2017-02-20 09:37:15.582587", "stderr": "F0220 09:37:15.841965   22124 image.go:99] ciao-cli FATAL: Could not create image [Post https://controller:9292/v2/images: dial tcp 10.103.239.202:9292: getsockopt: connection refused
...
```

I tried again and it worked.  It could be that the image service simply isn't ready when we try to upload the images.  This case is handled in SingleVM setup.sh by querying the image service in a loop until it is ready before uploading the images.  See https://github.com/01org/ciao/blob/master/testutil/singlevm/setup.sh#L703

**Comment by albertomurillo** [comment]
There are 3 possible solutions for this problem:

1) Run `ciao-cli image list` until it gets a response
2) Use ansible `wait_for` module as ```wait_for: host={{ controller_fqdn }} port=9292
3) Create proper services that notify systemd when they are ready to be used and return only then.

I would like to se #3 implemented and can start working on a patch for it. This way, `systemctl start ciao-controller` will return only when it is actually ready to serve responses.
