### ISSUE TITLE
Partial instance launching if there is a failure 

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#1203]
When requesting to launch multiples of an instance with --instances <n> and one of those instances errors out the started instances are left "hanging"; they are available in "ciao-cli instance list" but not reported in the output of ciao-cli instance add.

We have two options:

1. If any instance add fails, delete all the created instances and report the error directly.
2. Report the started instances and then report the failure via an event

To me the latter seems better.

**Comment by rbradford** [comment]
@kaccardi @tpepper architectural design feedback needed....

**Comment by tpepper** [comment]
I prefer option 2.
