### ISSUE TITLE
ciao-controller: Image ID is not shown when workloads listing

### ISSUE THREAD

**Issue by obedmr** [01org/ciao#1232]
ImageID is not shown when running:

```
ciao-cli workload list
```

Steps to reproduce it
----------------------
- Create a workload with this https://github.com/01org/ciao/blob/master/ciao-cli/examples/fedora_cloud.yaml
- Run ``ciao-cli workload list``

You will see this output:
```
Workload 1
        Name: Fedora VM no storage
        UUID:3f875e60-da16-46c9-8a9a-dfc60d790611
        Image UUID: 
        CPUs: 2
        Memory: 128 MB
```

**Comment by rbradford** [comment]
This issue was resolved by #1233
