### ISSUE TITLE
ciao-deploy: cleanup/ciao.yml playbook breaks when deploying from a target host

### ISSUE THREAD

**Issue by bwarden** [01org/ciao#1244]
I ran the cleanup/ciao.yml playbook from the ciao-deploy container, running _on_ the node I designated as controller. As part of the cleanup, the playbook apparently stopped the docker service on the controller node itself, killing the container from which I was running the playbook. We could document this as a limitation, but it would be nice to be able to deploy a cluster from one of the machines that will eventually be a part of it.

**Comment by tpepper** [comment]
@bwarden if you were using the ciao-deploy container based on some instance of current docu, can you let us know so we can fix it?

**Comment by bwarden** [comment]
Until the patch is pushed, the container is still in the public-facing documentation: https://clearlinux.org/documentation/ciao-deploy.html

**Comment by rbradford** [comment]
Ansible removed.
