### ISSUE TITLE
ciao-down 9pfs mount point (GOPATH) has some limitations

### ISSUE THREAD

**Issue by grahamwhaley** [01org/ciao#1261]
9pfs has some known 'filesystem anomolies', and as `ciao-down` uses 9pfs to mount the GOPATH, one should be aware that sometimes you might run into one.
In this instance, over at https://github.com/clearcontainers/osbuilder/issues/10 there is an example where a docker file based build system fails when on the GOPATH 9pfs, but works when moved to the $HOME vm filesystem.
Adding this issue to xref and make aware.

**Comment by rbradford** [comment]
Yup. I had problems when running the CC bats tests under the $GOPATH too.

**Comment by grahamwhaley** [comment]
I'll note here, that one other thing I did change in my local setup previously is to change the 9p mount security mount option from `model=passthrough` to `model=none` to enable my ciao-down VM root user to write root files to my host fs - which was required for another $GOPATH based program I was running (a test that needed to be run as root and be able to write its results file in the directory it was run from iirc).

**Comment by markdryan** [comment]
@grahamwhaley How would you like to see this fixed?  Change the 9p security_model from passthrough to none when booting CC vms?

**Comment by grahamwhaley** [comment]
Hi @markdryan . I think that would be the fix for one category of issues, but I don't think it fixes them all. For instance, I think I will have had that in place already when I got the osbuilder failures above.
What might be really nice is if we can set the 9p security model at ciao-down prepare time, and then users get to choose, and we could document that in the ciao-down instructions. Feasible?

**Comment by markdryan** [comment]
@grahamwhaley Sure.  That's easy to do.  It would still only be a partial fix though I guess.

**Comment by grahamwhaley** [comment]
Yep. It gives the option to enable a fix (with a bit of a security breach - hence an opt-in) for one set of issues.
Some of the other issues are know problems with 9pfs afaik (such as unlink sequencing problems stopping things like apt-get working if /tmp is a 9pfs mount) - I think that is a different class of problem, is currently inherent in 9pfs, and requires modifications to both the vm kernel and qemu to fix.
