### ISSUE TITLE
ciao-cli node list command doesn't work without template

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#1268]
tested on singlevm with ciao-down:
kcaccard@singlevm:~$ CIAO_USERNAME=$CIAO_ADMIN_USERNAME CIAO_PASSWORD=$CIAO_ADMIN_PASSWORD ciao-cli node list -cnci
F0501 20:57:19.691239   10893 node.go:81] ciao-cli FATAL: template node-list contains no source

I expected that this command would work without any template as I didn't pass the -f command and it used to work without a template.

**Comment by markdryan** [comment]
@kaccardi Are you testing with the latest version of the code?  This was broken a few weeks ago but I thought I'd fixed it.  Indeed ciao-cli node list -cnci is working for me.  Do you have https://github.com/01org/ciao/pull/1256 merged on your branch?

**Comment by tpepper** [comment]
And is this without pull #1193 ?

**Comment by rbradford** [comment]
Works here:

```
rob@singlevm:~/go/src/github.com/01org/ciao/testutil/singlevm$ git describe 
89-188-ga16660b
rob@singlevm:~/go/src/github.com/01org/ciao/testutil/singlevm$ CIAO_USERNAME=$CIAO_ADMIN_USERNAME CIAO_PASSWORD=$CIAO_ADMIN_PASSWORD ciao-cli node list --cnci
CNCI 1
	CNCI UUID: 9fecbbdd-0371-40c7-a906-5674e4d7440a
	Tenant UUID: f0c6ce88494e4af1a514b7b1e38f5cf2
	IPv4: 198.51.100.88
	Subnets:
		Subnet 172.16.0.0/8

```

**Comment by rbradford** [comment]
I'm pretty certain that this is fixed.
