### ISSUE TITLE
Support instance names

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#1270]
Currently the support for instance names is somewhat incomplete. At the very least we need to:

- persist in the database
- populate the openstack compute api when getting the instances
- support setting the name on the cli
- show the name in the cli
- support setting the name when creating instances (controller/API)
- handle clashes - names should be tenant unique
- create a useful name if user does not supply one

**Comment by tpepper** [comment]
Do we need to enforce "handle clashes - names should be tenant unique"?  I don't feel like that's a requirement enforced in other clouds and it would would annoy me as a user but I'm also quite possibly not 
a typical user.

**Comment by rbradford** [comment]
So I want to enforce that they are tenant unique so that you can reliably use them as DNS entries. To me it makes sense than the tenancy is a single DNS namespace. In the future we might add some kind of instance grouping that would allow us to relax this requirement.

Also I want to be able to say ciao-cli instance delete <name> and allowing clashes would increase the complexity of that somewhat. In my patch set if you request multiple instances with the same name i.e ciao-cli instance add -name foobar --instances 100 .... then the instances will be created as foobar-0, foobar-1,....foobar-99

**Comment by tpepper** [comment]
OK the DNS rationale makes a lot of sense.

What do you think of doing like AWS with name-XXXXXXXX eg: "ubuntuvm-51f7ced1"?  The fixed length is easier on the eyes in cli and we views and an ordering 0..N will get random probably over time as some long used instances hang around and other shorter lived ones come and go.
