### ISSUE TITLE
Link in README.md content missing

### ISSUE THREAD

**Issue by norbertfuhs** [01org/ciao#1346]
If you click on the link at the end of the readme to get to the comprehensive  [ciao cluster setup document](https://clearlinux.org/documentation/ciao-cluster-setup.html) the content is missing

**Comment by markdryan** [comment]
@norbertfuhs Yes you're quite correct and we already have a bug for this #1335.  We're currently in the process of changing our cluster deployment scripts and so the missing documents linked to by the README.md file are hopelessly out of date.  The best way to try ciao out at the moment is to use the ciao development environment.  It's easy to set up on linux and the docs should be up to date.

https://github.com/01org/ciao/blob/master/DeveloperQuickStart.md
