### ISSUE TITLE
ciao-down: create instances from workload files

### ISSUE THREAD

**Issue by devimc** [01org/ciao#1366]
would be nice to have an option to specify a custom workload file

**Comment by dlespiau** [comment]
We've discussed that in the past and we'd like to:

- allow relative/absolute paths to workload files
- allow the use of URLs for workload files
- maybe have a special ~/.ciao-down/workloads/ directory for user workloads

**Comment by markdryan** [comment]
> maybe have a special ~/.ciao-down/workloads/ directory for user workloads

This is already supported.  ciao-down looks here for workloads before looking in the Go path.  The other two aren't supported but should be easy and worthwhile to add.

**Comment by dlespiau** [comment]
The question now is, would supporting directly specifying a file be enough for your use case Julio?

**Comment by devimc** [comment]
@dlespiau yes, I plan to ship workload files in localCI, for that reason I need a way to specify a path to custom workloads
