### ISSUE TITLE
make test functionality global

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#137]
Many of us are duplicating effort writing fake schedulers, fake launchers, fake controllers to do unit testing.  In addition as we add more external component dependencies (like keystone) we have to fake those too.  We should create a "ciao-test" package that can provide this functionality so that we can all use it.

**Comment by tpepper** [comment]
Looks like it's called "testutil" and some things are starting to flow into it...

**Comment by kaccardi** [comment]
Assigning this to Tim as he has already started working on it in #179
