### ISSUE TITLE
kubicle fails without error message

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#1384]
kubicle can fail silently with an empty admin.conf and no explanation. If the VMs fail to init properly (due to errors encountered during cloud-init for example), there is no notification to the users.

**Comment by markdryan** [comment]
@kaccardi Is this happening a lot for you?  The only time I've seen it really fail is on k8s 1.7 or when I didn't give the ciao-down VM enough memory.  It needs about 6 GB.

Detecting an error on the master node should be easy enough, and is probably all we need to do, but this is not currently done.  If you do end up with an empty admin.conf file the only thing you can do at the moment is to ssh into the master node, 

```
ssh 198.51.100.2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/local/testkey
```

and have a look in /var/log/cloud-init-output.log

#1380 should probably go into the kubicle doc as well.  The short term work around for this one is to remove lines [6 to 11)[https://github.com/01org/ciao/blob/master/testutil/ciao-down/workloads/ciao.yaml#L6] in the ciao workload.

**Comment by kaccardi** [comment]
@markdryan I only tried it once, using the memory recommendations in the kubicle tutorial. I deleted the kubernetes cluster and reran kubicle and it worked after that. I'm going to experiment some to see if this is a consistent problem, or if I just got unlucky.
