### ISSUE TITLE
verify.sh fails with CNCI ping timeout after restart

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#1414]
FATAL ERROR exiting:  Unable to ping CNCI after restart 1

**Comment by kaccardi** [comment]
This happened within ciao-down.

**Comment by kaccardi** [comment]
Increasing the ping timeout has no effect - the CNCI is not responding to network traffic.

**Comment by kaccardi** [comment]
you can duplicate this outside of verify.sh by starting a single instance, finding the cnci ip with ciao-cli, then ssh'ing to the cnci and telling it to reboot now. it never returns.

**Comment by kaccardi** [comment]
git revert -m 1 730416be70d7031bf18e6730d66f30453c3691a2 works.

**Comment by rbradford** [comment]
@kaccardi I've seen that test flake often before we switched to go 1.9. After the switch to 1.9 @markdryan saw it consistently. After 0a6a18d630070bddada10572ea2a481345cf5e26 it *feels* like the flake happens less frequently. However I did see it on a couple of semaphore builds yesterday.

e.g. Here is a example of it happening before 1.9: https://semaphoreci.com/kaccardi/ciao/branches/pull-request-1410/builds/10

**Comment by rbradford** [comment]
Another datapoint on this. When I connect to the console of the CNCI and then trigger a reboot i see it shutdown, then the "screen" changes colour (I think that's from the OVMF firmware) and then it doesn't come back.

If I reboot the Ubuntu VM I do see it come back when connected to the console via nc.

**Comment by rbradford** [comment]
So I think wasn't being patient enough with the CNCI reboot. Sometimes it can take a long time but it does eventually happen.

This reboot in particular took over two minutes:

```
 Sep 01 15:12:11 cnci-a0833e20f6294e2a9a5c09d3feacec7d-b00addb9 systemd-journald[137]: Journal stopped
 -- Reboot --
 Sep 01 15:14:23 cnci-a0833e20f6294e2a9a5c09d3feacec7d-b00addb9 systemd-journald[146]: Runtime journal (/run/log/journal/) is currently using
  724.0K.
```

**Comment by rbradford** [comment]
By contrast this one only took 11s!

```
Sep 01 15:43:54 cnci-a0833e20f6294e2a9a5c09d3feacec7d-b00addb9 systemd-journald[146]: Journal stopped
-- Reboot --
Sep 01 15:44:05 cnci-a0833e20f6294e2a9a5c09d3feacec7d-b00addb9 systemd-journald[140]: Runtime journal (/run/log/journal/) is currently using 724.0K.
```

**Comment by rbradford** [comment]
After the revert in PR #1415 I see very consistent reboot times of < 10s. Now we have a workaround for the cnci agent to pull from /dev/urandom directly we can revert.

**Comment by markdryan** [comment]
> So I think wasn't being patient enough with the CNCI reboot. Sometimes it can take a long time but it does eventually happen.

This is what I've been seeing as well.  verify.sh can fail after the CNCI reboot.  But then if I wait a little bit after verify.sh has failed and then ping the CNCI it does work.  This is why I increased the timeout, but this was always only a hack.

**Comment by markdryan** [comment]
Looking at the CNCI syslogs I also see what @rbradford is seeing.  Sometimes it takes 20 seconds for the CNCI to reboot.  Sometimes it takes 2 minutes.  When it takes 2 minutes, verify.sh fails but the CNCI does become pingable shortly after.
