### ISSUE TITLE
CIAO- CN api returning null instead of empty list

### ISSUE THREAD

**Issue by leoswaldo** [01org/ciao#166]
CN api returning null instead of empty list

`openstack --debug server list`  if a tenant has no  instances/vms it returns: 

`RESP BODY: {"total_servers":0,"servers":null} `

Which is not compatible with novaclient, since http://git.openstack.org/cgit/openstack/python-novaclient/tree/novaclient/base.py line 259  expects a iterable.

When a project does not have any instance, it should return` {"servers": [], ...}`, where servers is a empty list, so novaclient can iterate in that (empty list), otherwise it would cause a "**'NoneType' object is not iterable**"

**Comment by jorgevgut** [comment]
Having iterables objects would actually benefit the UI, processing an empty array instead of a null object is easier to handle. UI should support this change, in case it do not I'll raise an issue, as this should be the expected behavior.

**Comment by sameo** [comment]
@jorgevgut @leoswaldo I suppose it would even be more confusing if the array did not appear at all, like e.g. `{"total_servers":0}` instead of `{"total_servers":0, servers: null}` ?

**Comment by leoswaldo** [comment]
@sameo it'd be nicer a empty list :)
