### ISSUE TITLE
Identify list of dependencies that can be eliminated

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#173]
And remove them.  The idea is to try to reduce the amount of 3rd party code we need to vendor and maintain.

**Comment by markdryan** [comment]
Here are a list of dependencies that are used only by ciao (and not by any vendored 3rd party dependencies).  

* github.com/01org/ciao/vendor/github.com/boltdb/bolt
* github.com/01org/ciao/vendor/github.com/coreos/go-iptables/iptables
* github.com/01org/ciao/vendor/github.com/davecgh/go-spew/spew
* github.com/01org/ciao/vendor/github.com/docker/distribution/uuid
* github.com/01org/ciao/vendor/github.com/docker/docker/pkg/jsonmessage
* github.com/01org/ciao/vendor/github.com/docker/engine-api/client
* github.com/01org/ciao/vendor/github.com/docker/libnetwork/drivers/remote/api
* github.com/01org/ciao/vendor/github.com/docker/libnetwork/ipams/remote/api
* github.com/01org/ciao/vendor/github.com/golang/glog
* github.com/01org/ciao/vendor/github.com/gorilla/mux
* github.com/01org/ciao/vendor/github.com/mattn/go-sqlite3
* github.com/01org/ciao/vendor/github.com/rackspace/gophercloud/openstack
* github.com/01org/ciao/vendor/github.com/tylerb/graceful
* github.com/01org/ciao/vendor/github.com/vishvananda/netlink
* github.com/01org/ciao/vendor/gopkg.in/yaml.v2

Some of these dependencies provide core functionality and so cannot really be removed.  Candidates for removal are then:

* github.com/01org/ciao/vendor/github.com/boltdb/bolt
* github.com/01org/ciao/vendor/github.com/davecgh/go-spew/spew
* github.com/01org/ciao/vendor/github.com/docker/distribution/uuid
* github.com/01org/ciao/vendor/github.com/docker/docker/pkg/jsonmessage
* github.com/01org/ciao/vendor/github.com/gorilla/mux
* github.com/01org/ciao/vendor/github.com/tylerb/graceful

It's probably too much work in the short term to remove 

* github.com/01org/ciao/vendor/gopkg.in/yaml.v2
* github.com/01org/ciao/vendor/github.com/mattn/go-sqlite3

Even if we switch from YAML to JS, launcher still needs a yaml parser for cloudinit.  Replacing sqlite3 would require a re-work of all controller's queries.

**Comment by sameo** [comment]
I'd want to keep gorilla/mux. It may not be a core feature, but we heavily use mux specific features for implementing the compute API.

**Comment by markdryan** [comment]
@sameo  Fair enough.  Just out of a matter of interest are there things that gorilla gives us that can't be easily done with the standard http package?

**Comment by sameo** [comment]
@markdryan the main feature missing from the standard http package is the quite powerful URL routing.

**Comment by markdryan** [comment]
We can't easily get rid of github.com/01org/ciao/vendor/github.com/docker/docker/pkg/jsonmessage either.

So this leaves

* github.com/01org/ciao/vendor/github.com/boltdb/bolt
* github.com/01org/ciao/vendor/github.com/davecgh/go-spew/spew
* github.com/01org/ciao/vendor/github.com/docker/distribution/uuid
* github.com/01org/ciao/vendor/github.com/tylerb/graceful

**Comment by markdryan** [comment]
@sameo, @mcastelino , @tpepper , @kaccardi any objection to removing the four packages listed above.  This will reduce our vendored package count by 5 and will reduce our total code count by 4000 lines of code minus the amount of code I need to add to remove the packages.  These are the low hanging fruit we should be able to do without.  If you're all in agreement, I'll close this ticket and open 4 separate ticket to remove the packages listed above.

**Comment by mcastelino** [comment]
@markdryan boltdb seems to be a pretty well maintained package and used quite a bit in the go community. Do you have a particular reason to remove it. It will require quite a bit of work on my side to replace it with our own custom implementation.

**Comment by markdryan** [comment]
@mcastelino Well we have this objective to remove any dependencies we can do without.  I guess the rational would be does it really make sense for ciao to use two different DBMSs.  Does it do something that we cannot do with sqlite3?  Note, I'd do the work to remove the code and replace it with either sqlite3 or something proprietary.  You'd just need to okay the patch.

**Comment by mcastelino** [comment]
@markdryan This is a simple transactional Key Value DB which supports concurrency vs a full fledged. Also there would be a instance of this needed on each and every compute node. That is the reason I did not choose to use sql lite.

**Comment by markdryan** [comment]
I don't think it would be a problem having a separate sqlite3 database one each node.  There are probably hundreds of these database on every android phone, so it shouldn't be too heavy for a compute node.

However, looking at this another way, boltdb pulls in about 4000 lines of go code and has no dependencies.

sqlite3 pulls in 1300 lines of go code and 114000 lines of C.  Although, it would be more work for us to replace sqlite3, from a security point of view and from the point of view of reducing the overall amount of code we vendor, this might be the better option.

Let's postpone the database decision for now.  I'll do some research to see how hard this would be.

So any objection to removing the following three dependencies right now?

```
github.com/01org/ciao/vendor/github.com/davecgh/go-spew/spew
github.com/01org/ciao/vendor/github.com/docker/distribution/uuid
github.com/01org/ciao/vendor/github.com/tylerb/graceful
```

**Comment by kaccardi** [comment]
for the record, I have no objection to using something other than sqlite3. The controller datastore is designed for a future in which we have different databases doing our persistent storage. However, I did this because I imagined we might need a *more* performant/secure database such as postgres in the future - I wasn't sure how sqlite3 would scale.

**Comment by markdryan** [comment]
Closing as the work to identify the dependencies that can easily be removed has been done.  See #220, #221 and #222.
