### ISSUE TITLE
CIAO use Keystone for projects/tenants handling

### ISSUE THREAD

**Issue by leoswaldo** [01org/ciao#190]
CIAO is using sqlite to store tenants/projects in its own side, projects being a common asked resource should be stored only in one database, so any service calling/requesting data about them must 100% accurate for any service.
CIAO projects handling should be delegated to keystone.

**Comment by kaccardi** [comment]
We cache tenant/project information to provide the level of performance that we require.  Can you please let me know what specific problem you are seeing?

**Comment by leoswaldo** [comment]
Rally benchmarking simulates real user load.  
Boot scenario creates a temporal project through Keystone API, then sends the workload to with project-id to compute API, which CIAO tries to verify it using its own sqlite database, so it does not make match because  CIAO's database does not have the project created through Keystone API, therefore rally cannot continue because of that.

**Comment by kaccardi** [comment]
The flow you described is not correct.  If a workload is requested to be started and the tenant information is not in ciao's cache, the tenant information will be added and the start workload will be allowed to proceed. So there is another reason why this call is failing, and we should debug that. Can you tell me what the exact api rally is using and what the response code is?

**Comment by tpepper** [comment]
The ciao-controller doc.go should describe the caching, how coherency is maintained, that our API support isn't yet complete, and how to debug a problem.

**Comment by leoswaldo** [comment]
@kaccardi  you are right, I tried to make a whole new test, restarting everything in my environment, and now it shows the adding process as you mentioned. 
Now I can see the  

```
exec: INSERT or IGNORE into tenants VALUES ('7cbb7a272bbe4e4a9c6a30b2be946dd2','','',$
02:c7:a0:40:0b:f1',''); 
```

My environment must had gone into a wrong state because it wasn't happening, but glad it works now. Now I'm into https://github.com/01org/ciao/issues/166, I'm taking a look into it, see if I can contribute on that.
I'm closing this issue,  +1 for @tpepper  comment

Thanks guys
