### ISSUE TITLE
Update rackspace/gophercloud to pickup Cinder v2 support

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#191]
I would like to update the vendored rackspace/gophercloud code to the latest HEAD to pick up the Block Storage v2 api support.

**Comment by albertomurillo** [comment]
So gophercloud was updated to support BlockStorage v2 api but the blockstorage files were left out
There is no openstack/blockstorage/v2 folder under vendor/github.com/rackspace/gophercloud/openstack

**Comment by markdryan** [comment]
@albertomurillo The vendoring tool only vendors packages that are actually used by the current ciao code base.  For it to vendor the github.com/rackspace/gophercloud/openstack package we'd need to first add some code to ciao (or one of its dependencies) that imports that package.
