### ISSUE TITLE
Fix CONFIGURE scheme

### ISSUE THREAD

**Issue by sameo** [01org/ciao#232]
Both the subnets (compute and mgmt) should be a list of subnets.

**Comment by mrkz** [comment]
@sameo  could you please elaborate more the description of this payload change?
(E.g: how's the current specification of both **`mgmt_net`** and **`compute_net`** and how would look the desired specification).

**Comment by sameo** [comment]
@mrkz I told you I will forget ;)

Both `mgmt_net` and `compute_net` fields will follow the same schema. Let me take `mgmt_net` as an example:
* Today is can only represent one subnet, e.g. `"mgmt_net": "192.168.1.0/24".
* We want to extend it to support a list of subnets, e.g. `"mgmt_net": ["192.168.1.0/24", "192.168.2.0/24"]`

**Comment by mrkz** [comment]
@sameo It makes sense.
Question now is have you thought of any preference on which parameter would be selected from the list? 
(e.g: ciao-launcher as of now takes both `mgmt_net` and `compute_net` as a plain string and applies them, but with this change more than 1 option would be available, how the decision would be taken to apply `mgmt_net` and `compute_net` values?)
Or maybe I'm missing some implementation  change which I have not seen yet :)

**Comment by sameo** [comment]
@mrkz Yes, sorry for the lack of explanation: The actual [libsnnet API](https://github.com/01org/ciao/blob/master/networking/libsnnet/cn.go#L36) takes a slice of subnets as an input, and then ciao-launcher [currently builds a slice with only one entry](https://github.com/01org/ciao/blob/master/ciao-launcher/network.go#L43).

So we want to modify ciao-launcher to take a slice of subnets and build a slice of CIDR to pass to libsnnet.
