### ISSUE TITLE
testing: add -race to .travis.yml and test-cases

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#235]
We can't simply add -race to .travis.yml as test-cases must pass it through.

And if we add it, we surely have some currently undetected data races.  So travis would fail and nothing would merge for a while.

I will experiment with this, find and fix issues, get us to a clean state, then enable the test support and submit a PR on a patchset.

**Comment by amyleeland** [comment]
Tried and failed here, moving this to backlog to revisit

**Comment by tpepper** [comment]
Issue #868 is an instance of a -race detected issue.
