### ISSUE TITLE
Smart default for certificate paths

### ISSUE THREAD

**Issue by sameo** [01org/ciao#254]
If SSNTP clients or servers start without providing a CA and private key paths, we should at least look for them in a default directory like e.g. /etc/pki/ciao/.
If there are 2 certificates there, one of them being a CA and the other one a private key we should try using them if they match.

**Comment by obedmr** [comment]
@sameo I think it was addressed at https://github.com/01org/ciao/commit/b82f3cc716e861a0c05d7ddbff805775b3b59f2c, right?

**Comment by sameo** [comment]
Closed with b82f3cc.
