### ISSUE TITLE
ciao-launcher: allow hard-reset without configuration

### ISSUE THREAD

**Issue by mcastelino** [01org/ciao#261]
Currently calling the hard-reset fails on a multi homed systems. This is due to the fact that the configuration is not available when performing hard reset. 

Due to this the network interfaces do not get cleaned up.

Hence we need to perform reset even if the CN init fails.

Hence we should remove this check
https://github.com/mcastelino/ciao/blob/master/ciao-launcher/main.go#L559

and always perform reset even if networking  is not set.

	glog.Info("Reset networking")

	err := cnNet.ResetNetwork()
	if err != nil {
		glog.Warningf("Unable to reset network: %v", err)
	}

**Comment by markdryan** [comment]
@mcastelino It looks like this one has been fixed.  Could you confirm?

**Comment by mcastelino** [comment]
@markdryan this has been fixed. We can close this
