### ISSUE TITLE
documentation: cluster config doc needs updated for ciao-cli subcommands

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#270]
https://clearlinux.org/documentation/ciao-cluster-setup.html includes reference to ciao-cli commands.  Since https://github.com/01org/ciao/pull/224 the ciao-cli command line has changed and is not backwards compatible.  The documentation in https://github.com/01org/ciao was changed, but the external docu has not been yet and needs done.

**Comment by markdryan** [comment]
It's not just the sections on ciao-cli that need to be updated.  The configuration changes and the resulting changes to the command line arguments of the various components require updates as well.  The instructions given to run launcher simply won't work any more.

**Comment by tpepper** [comment]
I'll open a separate issue for @obedmr to address the config changes in the doc

**Comment by tpepper** [comment]
https://github.com/01org/ciao/issues/274 opened to track the other changes for configuration parameters

**Comment by albertomurillo** [comment]
A PR is open for ciao documentation.

**Comment by obedmr** [comment]
@obedmr working on configuration package integration changes

**Comment by obedmr** [comment]
This is done, just waiting the documentation rebuild. It should happen by EOD
