### ISSUE TITLE
documentation: cluster config doc needs updated for configuration changes

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#274]
https://clearlinux.org/documentation/ciao-cluster-setup.html includes reference to the ciao-cert command and various ciao component command line invocations. Since #224 these command lines have changed and are not backwards compatible. The documentation in https://github.com/01org/ciao was changed to cover the new simplified cluster configuration defaults and override /etc yaml, but the external docu has not been yet and needs done.

**Comment by obedmr** [comment]
This is done, just waiting the documentation rebuild. It should happen by EOD
