### ISSUE TITLE
testing: identity test server coverage

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#345]
Ciao-controller's test identity server was moved to testutil/ but had only partial test coverage.  Adding coverage of the GET/POST handlers would increase test coverage by a statistically significant amount.

**Comment by tpepper** [comment]
NOTE: coverage might better come along with a refactor that splits out the way we deal with identity into something generic.  That something could have test coverage, and be backable by Keystone or the fake testutil/identity.go or something else for an identity server.

**Comment by rbradford** [comment]
Code has been removed by #1410
