### ISSUE TITLE
testing: compute service coverage

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#346]
Much of the payloads/compute.go functions are arguably covered, but the coveralls tool isn't noticing. The gap there points at payloads/compute.go and ciao-controller/compute*.go really should be a package of their own focused on exposing an OpenStack Compute API on top of Ciao.  @kaccardi has expressed a desire to do some cleanup in this direction.

There's as much as 400 lines of code here not covered by test, which is statistically significant in our test coverage percentage.

**Comment by kaccardi** [comment]
payloads/compute.go is being deleted as part of #406
