### ISSUE TITLE
Implement an event log retrieval endpoint

### ISSUE THREAD

**Issue by sameo** [01org/ciao#36]
That debug endpoint would allow us to fetch all controller received events.

**Comment by dlespiau** [comment]
Another random remark (sorry!): It could be nice to support some sort of distributed logging to follow what happens across the cluster. There are various thingies based on a google whitepaper around, AppDash being one written in go:

http://research.google.com/pubs/pub36356.html
https://github.com/sourcegraph/appdash

**Comment by sameo** [comment]
This was implemented with commit 931f870c1751d74b5e66849a6eeea509a33f66bf
