### ISSUE TITLE
Not able to list tenants with ciao-cli. Tenants are listed only after listing workloads or quotas

### ISSUE THREAD

**Issue by chavafg** [01org/ciao#38]
root@sn-controller ~/bin # ./ciao-cli -password hello -username csr -identity https://sn-keystone.zpn.intel.com:35357 -list-tenants  

root@sn-controller ~/bin # ./ciao-cli -password hello -username csr -identity https://sn-keystone.zpn.intel.com:35357
 -list-quotas -tenant 92834d7fd3494ef994e421fdb3eff3a9                                                               
Quotas for tenant 92834d7fd3494ef994e421fdb3eff3a9:
        Instances: 0 | Unlimited
        CPUs:      0 | Unlimited
        Memory:    0 | Unlimited
        Disk:      0 | Unlimited

root@sn-controller ~/bin # ./ciao-cli -password hello -username csr -identity https://sn-keystone.zpn.intel.com:35357 -list-tenants                                                                                                       
Tenant 1
        UUID: 92834d7fd3494ef994e421fdb3eff3a9
        Name:

**Comment by sameo** [comment]
This should be fixed with commit ae95ee0cdf498e35ec625ed3a1c49f2aa7d4d97d
