### ISSUE TITLE
Implement persistent data storage for ciao-image

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#384]
Implement the ciao-image datastore interface to store data persistently.

**Comment by amyleeland** [comment]
May not complete this Sprint

**Comment by markdryan** [comment]
@kaccardi, @obedmr  Is this a duplicate of #632?

**Comment by obedmr** [comment]
@kaccardi @markdryan I'd say yes, it's duplicated.

**Comment by obedmr** [comment]
Implemented on #632
