### ISSUE TITLE
Add image support to ciao-cli

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#386]
Add support for the ciao image service - using glance APIs if possible.

**Comment by sameo** [comment]
@kaccardi This is long time pending work that's currently waiting in https://github.com/01org/ciao/tree/sameo/topic/glance.
We will create a PR for this, together with pulling the recently added gophercloud image service support code into our vendored gophercloud.

**Comment by sameo** [comment]
This was closed with PR #398 merge.
