### ISSUE TITLE
Add volume support to ciao-cli

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#387]

**Comment by kaccardi** [comment]
This support includes modifying any existing calls to Open Stack compute APIs, adding new calls to Open Stack compute APIs, or any Block API calls that need to be made.

**Comment by kaccardi** [comment]
partially complete. Support for new volume functionality added, however, modification of existing calls to compute api is not done.

**Comment by tpepper** [comment]
When doing instance add, create volume dynamically at the same time.

**Comment by tpepper** [comment]
Addressed by https://github.com/01org/ciao/pull/896
