### ISSUE TITLE
add discovery of storage cluster to ciao configuration

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#388]
Add discovery of storage cluster (storage url and cephx secrets in ssntp configuration frame)
Add mountpoint for cephfs based storage at /var/lib/ciao to contain images/logs/etc. and mount cephfs there.

**Comment by sameo** [comment]
@kaccardi Could you please share what a ceph monitor URL would look like ?

Also, I think the cephfs mounting itself should be done by ciao-launcher, after receiving the configuration data. What do you say @markdryan ?

**Comment by kaccardi** [comment]
@sameo is this complete then?

**Comment by sameo** [comment]
Yes, this is complete.
