### ISSUE TITLE
Update PublicIP documentation in payloads

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#397]
When we initially added the documentation for payloads we just added a generic sentence for all the PublicIP types, e.g.,

```
// PublicIPEvent is reserved for future use.
```
This was done in commit  01d7e12d1e98e83dc26791ff303bbeee5b02ae9e.

These comments need to be update correctly to reflect the real purpose of the types that are documented.

**Comment by amyleeland** [comment]
Documents should be complete this week
