### ISSUE TITLE
Error when running cleanup_cluster playbook

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [01org/ciao#414]
When I try to clean up my CIAO cluster running the cleanup_cluster playbook, I receive the following error

TASK [Remove CIAO files from github] *******************************************
fatal: [192.168.122.148]: FAILED! => {"failed": true, "msg": "The conditional check 'ciao_dev' failed. The error was: error while evaluating conditional (ciao_dev): 'ciao_dev' is undefined\n\nThe error appears to have been in '/root/ciao/cleanup_ciao.yml': line 33, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Remove CIAO files from github\n      ^ here\n"}
fatal: [192.168.122.149]: FAILED! => {"failed": true, "msg": "The conditional check 'ciao_dev' failed. The error was: error while evaluating conditional (ciao_dev): 'ciao_dev' is undefined\n\nThe error appears to have been in '/root/ciao/cleanup_ciao.yml': line 33, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Remove CIAO files from github\n      ^ here\n
"}
fatal: [192.168.122.190]: FAILED! => {"failed": true, "msg": "The conditional check 'ciao_dev' failed. The error was: error while evaluating conditional (ciao_dev): 'ciao_dev' is undefined\n\nThe error appears to have been in '/root/ciao/cleanup_ciao.yml': line 33, column 7, but may\nbe elsewhere in the file depending on the exact syn tax problem.\n\nThe offending line appears to be:\n\n\n    - name: Remove CIAO files from github\n      ^ here\n"}

**Comment by albertomurillo** [comment]
This is not a CIAO issue

This is an issue with the playbooks which are hosted in other repository
Please open an issue there

https://github.com/clearlinux/clear-config-management

**Comment by arturo-garcia-garcia** [comment]
Sorry, my bad there, thanks, I'll open it in the right project
