### ISSUE TITLE
travis network unit test failures after docker update

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#420]
Network unit tests are not working with the latest version of docker.  We've got https://github.com/01org/ciao/pull/419/commits/09fa87eb5671b5418817b999c1df48c12c71ff55 which works around the issue.  But we should find the underlying issue and remove that workaround.

**Comment by mcastelino** [comment]
@tpepper @markdryan 

There are two issues here.

1. Switching back to the default http server (vs graceful) breaks unit test cases as we can no longer stop and start the plugin (which is done for each test run).

2. There seems to be an issue with the plugin to docker engine interface which can also be simulated manually using the standalone test plugin

sudo docker network create -d=ciao --subnet=192.168.50.0/24 --gateway=192.168.50.1 --opt bridge=testbr testbr
An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/networks/create: EOF

The details of the error within the docker-engine 
time="2016-08-01T15:10:01.966433873-07:00" level=debug msg="libcontainerd: containerd connection state change: READY"
time="2016-08-01T15:16:20.696703390-07:00" level=debug msg="Calling POST /v1.24/networks/create"
time="2016-08-01T15:16:20.696997434-07:00" level=debug msg="form data: {\"CheckDuplicate\":true,\"Driver\":\"ciao\",\"EnableIPv6\":false
,\"IPAM\":{\"Config\":[{\"Gateway\":\"192.168.50.1\",\"Subnet\":\"192.168.50.0/24\"}],\"Driver\":\"default\",\"Options\":{}},\"Internal\
":false,\"Labels\":{},\"Name\":\"testbr\",\"Options\":{\"bridge\":\"testbr\"}}"
2016-08-01 15:16:20.699321 I | http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 94 [running]:
net/http.(*conn).serve.func1(0xc820ac4100)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1a52560, 0xc8200100b0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/docker/docker/pkg/plugins.readPluginJSONInfo(0xc8209a0a88, 0x4, 0xc82020fe80, 0x1d, 0x0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/discovery.go:119 +0x221
github.com/docker/docker/pkg/plugins.(*localRegistry).Plugin(0xc820d8e8b8, 0xc8209a0a88, 0x4, 0x30, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/discovery.go:80 +0xa65
github.com/docker/docker/pkg/plugins.loadWithRetry(0xc8209a0a88, 0x4, 0x1, 0x0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:172 +0xa2
github.com/docker/docker/pkg/plugins.load(0xc8209a0a88, 0x4, 0xc8209a0a88, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:163 +0x3c
github.com/docker/docker/pkg/plugins.get(0xc8209a0a88, 0x4, 0x110, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:211 +0xe3
github.com/docker/docker/pkg/plugins.Get(0xc8209a0a88, 0x4, 0x1d4c2c0, 0xd, 0xc8204ba750, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:216 +0x4f
github.com/docker/libnetwork.(*controller).loadDriver(0xc820248960, 0xc8209a0a88, 0x4, 0x0, 0x0)
        /usr/src/docker/vendor/src/github.com/docker/libnetwork/controller.go:994 +0x53
github.com/docker/libnetwork.(*network).resolveDriver(0xc820ac3680, 0xc8209a0a88, 0x4, 0x1, 0x0, 0x0, 0x20, 0x0, 0x0)
        /usr/src/docker/vendor/src/github.com/docker/libnetwork/network.go:670 +0xea
github.com/docker/libnetwork.(*controller).NewNetwork(0xc820248960, 0xc8209a0a88, 0x4, 0xc8209a0b96, 0x6, 0xc820573c00, 0x40, 0xc82020fc20, 0x4, 0x4, ...)
        /usr/src/docker/vendor/src/github.com/docker/libnetwork/controller.go:588 +0x3b8
github.com/docker/docker/daemon.(*Daemon).createNetwork(0xc8204ce1a0, 0x1, 0xc8209a0a88, 0x4, 0x0, 0xc8209a0ae8, 0x7, 0xc820ab2510, 0xc8201180e0, 0x1, ...)
        /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/network.go:260 +0xe26
github.com/docker/docker/daemon.(*Daemon).CreateNetwork(0xc8204ce1a0, 0x1, 0xc8209a0a88, 0x4, 0x0, 0xc8209a0ae8, 0x7, 0xc820ab2510, 0xc8201180e0, 0x1, ...)

**Comment by mcastelino** [comment]
This is a bug in the docker code base https://github.com/docker/docker/commit/b1e71bdd1d624e297509a62b072082524dc841fc

@tpepper we can wait for the next docker update to fix it, or have a workaround for now

**Comment by mcastelino** [comment]
should be fixed in docker 1.12.1 https://github.com/docker/docker/issues/25046
