### ISSUE TITLE
ciao-cli: panics if no tenant-name specified

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#432]
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x813480, 0xc820010080)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3e6
main.getTenant(0xc82000e18e, 0x4, 0xc82000e22e, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/ciao-19/src/github.com/01org/ciao/ciao-cli/identity.go:277 +0x94f
main.main()
	/builddir/build/BUILD/ciao-19/src/github.com/01org/ciao/ciao-cli/main.go:344 +0x12e

**Comment by albertomurillo** [comment]
This has been fixed in https://github.com/01org/ciao/issues/433
