### ISSUE TITLE
ciao-cli: hangs if keystone auth fails

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#433]
I still haven't figured out why, but sometimes my non-admin ciao-cli keystone auth's fail.  The cli command appears hung.  But if I go look at the keystone logs I see a tremendous continual spew of authentication errors as if ciao-cli (or gophercloud?) has errant auth failure retry logic.

**Comment by leoswaldo** [comment]
@tpepper @obedmr @albertomurillo   I think I'm facing same exact issue, not sure but high probability. I got same issue with Rally. Rally creates temporal users (non admin user as your case) to run its operations, and sends its token to perform the request but for some reason, ciao is always trying to match the TOKEN (of temporal user)  to see if it belongs to the 'admin' or 'service' project, which fails.

**Comment by tpepper** [comment]
An easy way to repro this is to not have a project.  For example if you follow the current (buggy) cluster setup documentation:

```
$ openstack service create --name ciao compute
$ openstack user create --password hello csr
$ openstack role add --project service --user csr admin
$ openstack user create --password giveciaoatry demo
$ openstack role add --project demo --user demo user
```

there is no "demo" project.  The cli enters a continuous loop bombarding the keystone server.

Simply adding the project, eg:
```
openstack project create --description "Demostration Tenant Project" demo
```
"fixes" the issue by not hitting whatever code path in the cli is broken.

**Comment by albertomurillo** [comment]
So keystone allows you to create a 'demo' user and assign it to the 'demo' project without checking that the 'demo' project in fact exists.

This might be a keystone bug too.
Will dig deeper after fixing the ciao-cli part

**Comment by albertomurillo** [comment]
ciao-cli is not hanging but is panicing

```
root@controller.example.com ~ # ciao-cli workload list
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6f3b60, 0xc420012130)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
main.getTenant(0xc42001016e, 0x4, 0xc4200101ce, 0x6, 0x0, 0x0, 0x428b6c, 0xc420072058, 0x1, 0x0, ...)
        /root/go/src/github.com/01org/ciao/ciao-cli/identity.go:277 +0x765
main.main()
        /root/go/src/github.com/01org/ciao/ciao-cli/main.go:344 +0xf4
```
        
This is because func getTenant in ciao-cli/identity.go is not validating the case
where a user does not belong to any project.

A fix is on its way to fail properly.

**Comment by albertomurillo** [comment]
A fix on the documentation to create the 'demo' project is also on its way.
