### ISSUE TITLE
Unable to launch new CNCIs when trying to launch instances with other tenants 

### ISSUE THREAD

**Issue by chavafg** [01org/ciao#44]
1. Launched docker and clear instances with tenant 92834d7fd3494ef994e421fdb3eff3a9. Instances were successfully created. 
2. Tried to launch instances with another tenant of the same user and failed with error: Unable to Launch Tenant CNCI. 
3. Tried to launch instances with the admin tenant and failed with same error as above. 

Below logs from cli and network node: 

- cli logs: 

root@sn-controller ~/bin # ./ciao-cli -password hello -username csr -identity https://sn-keystone.zpn.intel.com:35357 -tenant 92834d7fd3494ef994e421fdb3eff3a9 -launch-instances -workload ca957444-fa46-11e5-94f9-38607786d9ec 
Created new instance: 2369578a-8f12-4bf0-af1e-a129295427dc
root@sn-controller ~/bin # ./ciao-cli -password supernova -username admin -identity https://sn-keystone.zpn.intel.com:35357 -tenant d750a83434e941639ba0c3a37fe18efa -scope admin -launch-instances -workload e35ed972-c46c-4aad-a1e7-ef103ae079a2 
F0418 14:18:53.028643    3137 ciao-cli.go:109] ciao-cli FATAL: HTTP Error [500] for [POST https://localhost:8774/v2.1/d750a83434e941639ba0c3a37fe18efa/servers]: Unable to Launch Tenant CNCI
goroutine 1 [running]:
github.com/golang/glog.stacks(0xa60a00, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0xa447a0, 0xc800000003, 0xc8201c8fc0, 0xa26054, 0xb, 0x6d, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:720 +0x2ce
github.com/golang/glog.(*loggingT).printf(0xa447a0, 0x3, 0xc8200f45a0, 0x8f, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:655 +0x1d4
github.com/golang/glog.Fatalf(0xc8200f45a0, 0x8f, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:1148 +0x5d
main.fatalf(0xc8200e4680, 0x7f, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/ciao-cli.go:109 +0x89
main.createTenantInstance(0x7ffd87812721, 0x20, 0x7ffd8781276b, 0x24, 0x1)
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/ciao-cli.go:598 +0x473
main.main()
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/ciao-cli.go:807 +0x6b7

- Network node Error Log: 

Log file created at: 2016/04/18 14:01:51
Running on machine: sn-network
Binary: Built with gc go1.6 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0418 14:01:51.307449     588 network.go:287] cn.CreateCnciVnic failed cncivnic error: enable link up device or resource busy
E0418 14:01:51.307578     588 instance.go:134] Unable to start instance[network_failure]: cncivnic error: enable link up device or resource busy
E0418 14:13:51.977771     588 network.go:287] cn.CreateCnciVnic failed cncivnic error: enable link up device or resource busy
E0418 14:13:51.977792     588 instance.go:134] Unable to start instance[network_failure]: cncivnic error: enable link up device or resource busy
E0418 14:18:52.817650     588 network.go:287] cn.CreateCnciVnic failed cncivnic error: enable link up device or resource busy
E0418 14:18:52.817667     588 instance.go:134] Unable to start instance[network_failure]: cncivnic error: enable link up device or resource busy

- output from # ip -d link

root@sn-network ~ # ip -d link 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 addrgenmode eui64 
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0 promiscuity 0 
    ipip remote any local any ttl inherit nopmtudisc addrgenmode eui64 
3: wlp2s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 34:13:e8:36:b0:a0 brd ff:ff:ff:ff:ff:ff promiscuity 0 addrgenmode eui64 
4: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether b8:ae:ed:77:02:86 brd ff:ff:ff:ff:ff:ff promiscuity 0 addrgenmode eui64 
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:52:d2:61:8e brd ff:ff:ff:ff:ff:ff promiscuity 0 
    bridge forward_delay 1500 hello_time 200 max_age 2000 ageing_time 30000 stp_state 0 priority 32768 vlan_filtering 0 vlan_protocol 802.1Q addrgenmode eui64 
6: svc_6c531194@enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether 02:37:a6:4c:58:33 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap  mode vepa addrgenmode eui64 
    alias cncivnic_92834d7fd3494ef994e421fdb3eff3a9_044939c4-feff-447b-ac05-6e3ec8bacc2c
7: svc_bd5f8286@enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether 02:13:95:c5:51:f8 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap  mode vepa addrgenmode eui64 
    alias cncivnic_4e3290a89b764b979d508b22cef4048d_d1b20e75-a07f-471b-8315-d04095137235
8: svc_b4206548@enp0s25: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
    link/ether 02:13:95:c5:51:f8 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap  mode vepa addrgenmode eui64 
    alias cncivnic_4e3290a89b764b979d508b22cef4048d_7f1c862d-ba25-47f3-9f85-a86ea73d531a
9: svc_2c11fbc3@enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether 02:3d:80:f6:6f:40 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap  mode vepa addrgenmode eui64 
    alias cncivnic_d750a83434e941639ba0c3a37fe18efa_b479959c-99ee-4d59-9331-8b76e625225c
10: svc_44124e30@enp0s25: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
    link/ether 02:3d:80:f6:6f:40 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap  mode vepa addrgenmode eui64 
    alias cncivnic_d750a83434e941639ba0c3a37fe18efa_18e4cdca-4d6b-4078-87e7-f8ce647cc961
11: svc_9e0bcea4@enp0s25: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
    link/ether 02:3d:80:f6:6f:40 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap  mode vepa addrgenmode eui64 
    alias cncivnic_d750a83434e941639ba0c3a37fe18efa_aded9538-e4f4-49e5-97d7-9b9b014743c9

**Comment by mcastelino** [comment]
@chavafg can you check if you are having DHCP problems in your setup. I see this error only when the CNCI fails to obtain a DHCP lease and the controller then attempts to create a new CNCI as the first instance has not checked back in with the ciao-controller.

Note: We need to document this in known issues.

**Comment by tpepper** [comment]
Also if you use https://download.clearlinux.org/demos/ciao/clear-7470-ciao-networking.img.xz as the basis for your CNCI image (eg: create with https://github.com/01org/ciao/blob/master/networking/cnci_agent/scripts/update_cnci_cloud_image.sh), the CNCI should be a better network citizen and have less DHCP issues.

**Comment by mcastelino** [comment]
Not seen this error since the initial sighting. Please re-open if you can reproduce.
