### ISSUE TITLE
SingleVM SSH instance checks fail

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#493]
The SingleVM SSH instance checks are failing.  Once the setup.sh script has launched the VMs it tries to connect to the SSH port on one of those VMs to ensure SSH is working.  This is failing as the version of SSH has been updated in the clear image SingleVM uses for the VMs.  The setup.sh script is expecting to find

```
	if [[ "$ssh_check" == *SSH-2.0-OpenSSH_7.2* ]]
```
but what it's now getting is

SSH-2.0-OpenSSH_7.3

and so the tests fail, even though the script can connect to the SSH port.

**Comment by markdryan** [comment]
@obedmr Would you be interesting in looking at this as you have a SingleVM PR outstanding?  I guess you'll need to fix this before you can test your PR.

**Comment by obedmr** [comment]
Hey @markdryan, sure, yes, actually, I'm having that in the same [PR](https://github.com/01org/ciao/pull/449/commits/6db8f2ffb63c3189adbb6d7904aca16e7c1af85a#diff-04ed742f8328787431b9975d1866ffd2R293)
Would it be better if I separate it in a different PR?

**Comment by markdryan** [comment]
@obedmr Yes probably better to have two commits.

**Comment by obedmr** [comment]
Sure. Fixing it
