### ISSUE TITLE
osprepare prevents launcher from exitting cleanly

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#500]
osprepare.distro.InstallPackages needs to take a context parameter as its first argument so it can be cancelled.  It initiates a long running process that blocks the calling thread until it finishes.  This prevents launcher and the other ciao components from shutting down cleanly when asked to exit.

**Comment by tpepper** [comment]
I've got a patch which I think does the right thing, but need to test.

**Comment by markdryan** [comment]
Does the patch actually quit the installer?  I ask as I tried this today but I forgot to set my proxies so  nothing got installed.  When I tried to quit, launcher quit after 1 second (in an unclean fashion) but the apt-get install process launched by osprepare was still running and still outputting stuff to my terminal, which made it very hard to use.

**Comment by tpepper** [comment]
I'm using the context.WithCancel() as in your existing code, so if it's go's not actually quitting the sub-exec, then your existing calls are similarly persisting?
