### ISSUE TITLE
osprepare needs a logging abstraction

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#504]
osprepare is currently logging everything to stdout which isn't very useful when debugging an installation on a remote node.  I realise that we have an outstanding issue that the drive to which logs files are written might not be available when osprepare runs, but OS prepare shouldn't know or care about this.  It should simply provide an abstract logging interface in the same way that the ssntp and qemu packages do.  This way it can log what ever it likes to this interface and let it's clients worry about where the logs actually get written.  See the qemu and launcher for details about how to do this.

https://github.com/01org/ciao/blob/master/qemu/qmp.go#L56
https://github.com/01org/ciao/blob/master/ciao-launcher/qemu.go#L47

**Comment by bryteise** [comment]
Instead of adding another new logging abstraction, consolidate the launcher and qemu abstractions and introduce that abstraction into osprepare. Leave the other loggers alone for now.

**Comment by markdryan** [comment]
Fixed in PR #515
