### ISSUE TITLE
ciao-cli instance delete --all does not remove network interfaces

### ISSUE THREAD

**Issue by mcastelino** [01org/ciao#518]
After ciao-cli instance delete --all on a node the network interfaces created for the node are left behind.
This seems to be regression. This can be tested with the single vm script which tears down all the instances.
Nothing has changed in networking in a while.

**Comment by mcastelino** [comment]
@markdryan  The interface left behind is one of the interfaces created for the container. It looks like the last container interface is somehow not getting deleted. This leaves the tenant bridge and all the artifacts around. 

```
5520: sbr_8ca80dea: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:92:4b:05:a5:3a brd ff:ff:ff:ff:ff:ff
    alias br_f452bbc7-5076-44d5-922c-3b9d2ce1503f_172.16.0.0/24_f30d86d0-69a8-4024-851a-548c844d4e0d_198.51.100.64
5521: sgt_99d2ff65@NONE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1458 qdisc pfifo_fast master sbr_8ca80dea state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 5e:f1:a1:d1:89:15 brd ff:ff:ff:ff:ff:ff
    alias gre_f452bbc7-5076-44d5-922c-3b9d2ce1503f_172.16.0.0/24_f30d86d0-69a8-4024-851a-548c844d4e0d_198.51.100.64
5526: svp_28be5010@svn_28be5010: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:00:ac:10:00:04 brd ff:ff:ff:ff:ff:ff
5527: svn_28be5010@svp_28be5010: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master sbr_8ca80dea state UP mode DEFAULT group default
    link/ether 02:92:4b:05:a5:3a brd ff:ff:ff:ff:ff:ff
    alias vnic_f452bbc7-5076-44d5-922c-3b9d2ce1503f_172.16.0.0/24_f30d86d0-69a8-4024-851a-548c844d4e0d_198.51.100.64##172.16.0.4

```

**Comment by markdryan** [comment]
@mcastelino It's a race condition in setup.sh.  The script asks controller to delete the instances and then rather rudely removes the /var/lib/ciao/instances/ directory.  The problem is the ./ciao-cli --delete-all command returns before launcher has deleted all the instances.  By the time launcher actually gets around to deleting the instances (and their vnics), setup.sh has deleted its state.

```
E0905 17:28:12.190255    2817 vmconfig.go:51] Unable to open instance file /var/lib/ciao/instances/3a6c4217-e800-4c2a-b1e0-4b47b9b1a075/state
W0905 17:28:12.190342    2817 delete_instance.go:28] Unable to load instance state /var/lib/ciao/instances/3a6c4217-e800-4c2a-b1e0-4b47b9b1a075: open /var/lib/ciao/instances/3a6c4217-e800-4c2a-b1e0-4b47b9b1a075/state: no such file or directory
```

The quick fix is to simply remove the rm -rf /var/lib/instances.  If I do this, all that is left after the script exits is

```
10: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
11: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
```

**Comment by mcastelino** [comment]
This is due to a race condition in the script which does a rm -rf prior to the cluster shutdown.
This force clear is not needed and can be done cleanly at the start of the script with a hard reset vs a rm -rf. Will fix the script.
