### ISSUE TITLE
SingleMachine: Does not work on Fedora due to default firewall rules

### ISSUE THREAD

**Issue by mcastelino** [01org/ciao#526]
On Fedora the Single Machine tests do not work due to the default firewall rules.
The DHCP requests directed to the CNCI are blocked by the default firewall rules.

The single machine scripts should be modified to allow the local DHCP request into the CNCI VM.

A workaround for now is to temporarily stop firewalld

```
sudo systemctl stop firewalld
#And run the script
sudo systemctl start firewalld
```

**Comment by erick0z** [comment]
@mcastelino Regarding this topic. Is there a plan for handling the firewall from Ciao? Not only for fedora but other distros?

**Comment by tpepper** [comment]
@erick0z it's really hard to know what to do.  There's a tonne of different firewall tools in linux, and at the iptables level they implement "firewall" quite differently in terms of how they use the default tables and add interrelated chains to handle packet flows.  And other system tools tweek things too, eg: docker adds miscellaneous rules into the mix and dynamically manages them.

**Comment by tpepper** [comment]
I'm able to operate on Fedora with the following firewall additions, but note:  I'm not running the distro complex firewall.  I have a modestly complex, relatively restrictive, hand built /etc/sysconfig/iptables ruleset.

Prior to "setup.sh":
{code}
#!/bin/bash
iptables -I INPUT   1 -p tcp -m tcp --dport 8888 -j ACCEPT
iptables -I INPUT   1 -p 47 -j ACCEPT
iptables -I OUTPUT  1 -p 47 -j ACCEPT
iptables -I INPUT   1 -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -I OUTPUT  1 -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -I FORWARD 1 -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -I FORWARD 1 -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -I FORWARD 1 -p udp -m udp --dport 67:68 -j ACCEPT
iptables -I FORWARD 1 -p udp -m udp --dport 123 -j ACCEPT
iptables -I FORWARD 1 -p udp -m udp --dport 53 -j ACCEPT
iptables -I FORWARD 1 -p udp -m udp --dport 5355 -j ACCEPT
#iptables -I FORWARD 1 -p 2 -j ACCEPT
iptables -I FORWARD 1 -p icmp -j ACCEPT
{code}

and after "cleanup.sh":
{code}
#!/bin/bash
iptables -D INPUT   -p tcp -m tcp --dport 8888 -j ACCEPT
iptables -D INPUT   -p 47 -j ACCEPT
iptables -D OUTPUT  -p 47 -j ACCEPT
iptables -D INPUT   -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -D OUTPUT  -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -D FORWARD -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -D FORWARD -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -D FORWARD -p udp -m udp --dport 67:68 -j ACCEPT
iptables -D FORWARD -p udp -m udp --dport 123 -j ACCEPT
iptables -D FORWARD -p udp -m udp --dport 53 -j ACCEPT
iptables -D FORWARD -p udp -m udp --dport 5355 -j ACCEPT
#iptables -D FORWARD -p 2 -j ACCEPT
iptables -D FORWARD -p icmp -j ACCEPT
{code}

I'm not sure what's doing IGMP (protocol 2) inside the cluster.  I don't see anything not functioning without the addition of an ACCEPT rule for it.  But I do see packets logged on the virtual bridge when they hit my end reject rule in the nat table FORWARD chain if I don't accept them.

**Comment by kaccardi** [comment]
This issue is resolved by using ciao-down.
