### ISSUE TITLE
ciao-cli -list-tenants should not ask for a tenant to be passed as argument 

### ISSUE THREAD

**Issue by chavafg** [01org/ciao#53]
When having more than 1 tenants for a specific user, and trying to list the tenants, you are asked to specify the tenant. But since the tenant's list is the information you are looking for, you should not get  the next error:

root@sn-controller ~ # ./ciao-cli -list-tenants
Available projects for csr:
         Project[1]: ciao1 (4e3290a89b764b979d508b22cef4048d)
         Project[2]: service (92834d7fd3494ef994e421fdb3eff3a9)
F0421 13:11:04.421239   16964 main.go:67] ciao-cli FATAL: Please specify a project to use with -tenant-name or -tenant-id
goroutine 1 [running]:
github.com/golang/glog.stacks(0xa6ca00, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0xa507e0, 0xc800000003, 0xc8201e3080, 0xa31c88, 0x7, 0x43, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:720 +0x2ce
github.com/golang/glog.(*loggingT).printf(0xa507e0, 0x3, 0xc820016280, 0x4f, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:655 +0x1d4
github.com/golang/glog.Fatalf(0xc820016280, 0x4f, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:1148 +0x5d
main.fatalf(0x8d9a80, 0x3f, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/main.go:67 +0x89
main.main()
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/main.go:793 +0x5cf

**Comment by sameo** [comment]
Fixed with commit 24185e966f4117dae146fec77ef9cc7e78f2d59a.
