### ISSUE TITLE
ciao-controller: Add External IP Support - HTTPS Api

### ISSUE THREAD

**Issue by obedmr** [01org/ciao#532]
Implement HTTPS API for Assignment and release of external IPs

**Comment by jorgevgut** [comment]
Will floating ip support be exposed via an API? This is for future integration with Web UI.

**Comment by leoswaldo** [comment]
@jorgevgut yes, the idea is that the API will be exposed, we haven't defined the methods to expose yet

**Comment by kaccardi** [comment]
The OpenStack APIs for floating IPs don't map well to the ciao external IP architecture. We will not be implementing the OpenStack APIs, and will instead provide a set of ciao specific APIs.
