### ISSUE TITLE
Make SingleVM useful for development

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#536]
Right now SingleVM is more of a BAT test rather than a development environment.  When you start the single VM it creates 4 instances which have some quite heavy workloads.  Once these are finished it tears everything down.  As a developer, I would just like all the ciao services to be installed and to be able to run my own tests without having to wait for the standard SingleVM tests to complete.  I also I don't want everything pulled down.  Basically, I'd like an option so that the script stops after the ciao services have been started, and prints something out the stdout saying set these environment variables to use ciao-cli.

Also, I think this should be the default behaviour.  The current behaviour where we run all the tests should only be enabled if we specify a --bat flag.

**Comment by markdryan** [comment]
Perhaps we could simply place the bat tests in a separate script which could be run when singlevm starts up.  So maybe we could have

setup to initialise everything
run_bat to run the tests
teardown to stop everything

**Comment by markdryan** [comment]
The other thing that's a bit nasty about the script is that it temporarily modifies your /etc/hosts file.  This means that it can't be run directly on a development machine.  It needs to be run inside a VM or a container.  How far are we off getting all this to work inside a container?  Can we just put all this stuff inside an image and upload to docker hub?

**Comment by mcastelino** [comment]
@markdryan agree. Will add a BAT and standalone mode.

@kaccardi @tpepper We need a way to delete an tenant and associated CNCI to ensure the cluster can be torn down properly (vs just killing the CNCI).

The /etc/hosts change should not be required. We need to setup certificates and DNS resolution properly in both directions so that TLS will not complain.

**Comment by markdryan** [comment]
Most of this is already done.  We just need to make the automated tests optional.
