### ISSUE TITLE
ciao-cli should allow you to list service tenants using service user

### ISSUE THREAD

**Issue by chavafg** [01org/ciao#54]
with service user (csr), I am not able to list my own tenants, got a "not authorized" error. 

I should be able to get user's own tenants, right? 

root@sn-controller ~/supernova-test/functionalTests # export | grep CIAO
declare -x CIAO_COMPUTEPORT="8774"
declare -x CIAO_CONTROLLER="192.168.10.121"
declare -x CIAO_IDENTITY="https://sn-keystone.zpn.intel.com:35357"
declare -x CIAO_PASSWORD="hello"
declare -x CIAO_USERNAME="csr"
root@sn-controller ~/supernova-test/functionalTests # ./ciao-cli -list-tenants
F0421 19:26:11.505662   23758 main.go:67] ciao-cli FATAL: HTTP Error [403] for [GET https://sn-keystone.zpn.intel.com:35357/v3/projects]: {"error": {"message": "You are not authorized to perform the requested action: identity:list_projects", "code": 403, "title": "Forbidden"}}
goroutine 1 [running]:
github.com/golang/glog.stacks(0xa6ca00, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0xa507e0, 0xc800000003, 0xc8200e6300, 0xa31c88, 0x7, 0x43, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:720 +0x2ce
github.com/golang/glog.(*loggingT).printf(0xa507e0, 0x3, 0xc8203280f0, 0xeb, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:655 +0x1d4
github.com/golang/glog.Fatalf(0xc8203280f0, 0xeb, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/golang/glog/glog.go:1148 +0x5d
main.fatalf(0xc8200a27e0, 0xdb, 0x0, 0x0, 0x0)
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/main.go:67 +0x89
main.listAllTenants()
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/main.go:383 +0xcf
main.main()
        /home/fuentess/go/src/github.com/01org/ciao/ciao-cli/main.go:884 +0xc59

**Comment by sameo** [comment]
Fixed with commit 24185e966f4117dae146fec77ef9cc7e78f2d59a.
