### ISSUE TITLE
Enable TLS verification between ciao-cli and the controller

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#544]
Currently TLS verification is disabled when communicating with the controller. Here is the documentation for InsecureSkipVerify:

        // InsecureSkipVerify controls whether a client verifies the
        // server's certificate chain and host name.
        // If InsecureSkipVerify is true, TLS accepts any certificate
        // presented by the server and any host name in that certificate.
        // In this mode, TLS is susceptible to man-in-the-middle attacks.
        // This should be used only for testing.
        InsecureSkipVerify bool

On a cluster that we built with ansible recently, enabling TLS verification allows ciao-cli to communicate with the controller provided the CA is available.

**Comment by tpepper** [comment]
Is there a verb missing in the first sentence of the issue description?

**Comment by rbradford** [comment]
Thanks @tpepper. Fixed now. 

@markdryan thinks that there might be clusters our there there that rely on TLS verification being disabled.

My thought is to add a -disable-tls-verification command line option temporarily (with verification on by default) as an intermediate step to requiring TLS verification.

**Comment by mcastelino** [comment]
@rbradford the single machine setup today does not use TLS between cli and controller. So longer term we should either enhance Single machine to support TLS in Single machine between cli and controller.

**Comment by kaccardi** [comment]
sorry, we had to revert the PR that fixed this.
