### ISSUE TITLE
External IP Support: Controller, CLI and Web UI Requirements

### ISSUE THREAD

**Issue by mcastelino** [01org/ciao#556]
Folks,

Floating IP support is being enabled in the CNCI.
## Quick summary:
- SSNTP supports two commands today
  https://github.com/01org/ciao/blob/56930eab39e00665cbdcd9f56bd0748f3129ee67/payloads/assignpublicIP.go
  - CommandAssignPublicIP
  - CommandReleasePublicIP
- The CNCI will start supporting these two commands
- These two commands allow assignment of a Public IP to a given InstanceUUID
## What is a Public IP:
- A public IP can be any IP that is routable at the Data Center underlay (physical layer)
  - Hence it can be an internet routable IP or
  - A data center local IP which is only routable within the data center
- The CNCI is sitting on the underlay. Hence as long as the traffic makes it to the physical network segment on which the CNCI resides the CNCI will pick it up

Note: Routing of the data center traffic such that the public IP gets routed to the CNCI is outside the scope of Ciao today. BGP or OSPF can be setup on the NN to advertise the fact that a given NN is hosting a CNCI which is hosting a given public IP.
## Concepts:
- Public IP Pool: The pool of public IP's available to Ciao to assign to instances across tenants. The public IP pool is global to Ciao and _not_ tenant specific. 
  - The public IP pool can be specified in multiple formats
  - CIDR: a.b.c.d/p
  - Range: a.b.c.d-a.b.x.y
  - Individual IPs: a1.b1.c1.d1,a2.b2.c2.d2
- Ciao can have multiple pools at any given time
- Currently there are no plans to assign a pool to a tenant
- A tenant will not be able to choose an IP for a given instance
  - The tenant _may_ in the future get to choose which pool the IP can come from
    - Even in this case the pool will be an _abstract_ admin defined context
## Controller:

External API:
- should support creation of a pool of public IPs
- should support creation of multiple such pools
- should support assignment of public IP from a given pool to a given instance
- should support release of public IP from a given instance
- may support public IP stats
        - free/in use per pool

Note: In the first version we can support a single default pool for all tenants
## Internal Implementation
- Should pick a free IP from the pool and generate a CommandAssignPublicIP and send it to the CNCI belonging to that tenant
  - The controller decides the IP to assign (not the user)
- Should flag an error if the pool is exhausted
- in the future when we support multiple CNCI's per tenant, it should be sent to the CNCI hosting the instance
- Instance deletion handling
        - the controller should first release the public IP before deleting the instance
## WebUI
- should support creation of a pool (admin only)
- should support creation of multiple pools (admin only)
- should support display of available pools
- should support assignment of public IP to a given instance (tenant and admin)
- should support release of public IP from a given instance (tenant and admin)
- may support a admin view that shows Public IP mapping
      - IP stats (available, free)
      - within tenant (tenant view)
      - across tenants (admin view)
## Deletion of a pool
- Currently out of scope. But will involve freeing all instances with that IP and then deleting the pool
## ARP Impacts
- The public IP is mapped to the CNCI mac address (which the mac of the macvtap interface)
- The Public IP's migrate with the CNCI. Hence if a CNCI moves the Public IP moved with it.
- The public IP is held by the CNCI. Hence the CN's and instances do not get impacted and the instances can move around freely.
## Potential CLI

Pool Creation/Deletion

```
ciao-cli floatingip pool create  #returns pooluuid
ciao-cli floatingip pool delete -pool <pooluuid>
ciao-cli floatingip pool list
```

Pool Management

```
ciao-cli floatingip ip <add|delete> -pool <pooluuid> -subnet <a.b.c.d/p>
ciao-cli floatingip ip <add|delete> -pool <pooluuid> -ip <a.b.c.d>
ciao-cli floatingip ip <add|delete> -pool <pooluuid> -range <a.b.c.d-a.b.x.y>
ciao-cli floatingip ip list -pool <pooluuid>
```

IP Management

```
ciao-cli floatingip ip <assign|release> -pool <pooluuid> -instance <instanceuuid> #returns IP
ciao-cli floatingip ip release -pool <pooluuid> -all
ciao-cli floatingip ip list -instance <instanceuuid> [-pool <pooluuid>]
```

**Comment by kaccardi** [comment]
@mcastelino I assume that public IPs will have per tenant quotas in ciao? For example, will we allow restriction of the number of public IPs any given tenant is allowed to claim from the pool?

**Comment by mcastelino** [comment]
@kaccardi having quota's per tenant makes sense to prevent DoS attacks by a tenant. So we should consider adding it.

**Comment by tpepper** [comment]
While the external routing is out of scope currently...what can we do for testability?  Could the CNCI / NN at least do gratuitous ARP announcements upon CommandAssignPublicIP processing?

**Comment by mcastelino** [comment]
@tpepper the best way to test is to reserve a pool of IP's on the DHCP server servicing the underlay (in a lab setup that will be the bastion host). You will see no DHCP requests coming  out of the CNCIs.

Another option is to just choose a pool that the bastion will NAT out. So that the pool does not propagate out of the lab network.

The CNCI will answer ARPs on behalf of the IPs. Hence they will just show up as long as you are on same L2 broadcast domain.

A side note: 
The Public IP's migrate with the CNCI. Hence if a CNCI moves the Public IP moved with it.
The public IP is held by the CNCI. Hence the CN's and instances do not get impacted and the instances can move around freely.

**Comment by jorgevgut** [comment]
If we implement quotas, would these be tenant specific? or would it be a quota that an admin has across all projects?(I imagine the second as perhaps the "quota" for a tenant would be the pool itself) We'll need to show that too on the webui, all other info to show and manage in the UI make a lot of sense to me, thanks @mcastelino

**Comment by mcastelino** [comment]
@jorgevgut my personal preference is not to have tenant specific pools. But I can see how that can be another way to do quotas. Public IPs are a valuable resource and I rather not have a tenant lock them up. It will be better if the controller just hands them out on a need basis. Also I feel a per tenant pool adds more complexity without a significant benefit.

**Comment by jorgevgut** [comment]
Another question/idea, should we keep track of use of the IPs. For instance, keeping historical data to know how much IPs from the pool have been used (by which tenants) and for what period of time?

**Comment by mcastelino** [comment]
@jorgevgut @kaccardi tracking of IPs and historical data makes sense. However I would defer to @kaccardi on how to support it as only the controller has this information.

**Comment by kaccardi** [comment]
@jorgevgut we can easily treat the IPs the way we do any other resource as far as limits/total count of usage goes. Keeping historical stats (i.e. with time associated with them) would be more difficult. How do you image the user utilizing this info?

**Comment by mcastelino** [comment]
@sameo Added CLI details. can you review the potential CLI implementation

**Comment by sameo** [comment]
@mcastelino The CLI plans look good to me.

**Comment by tpepper** [comment]
@sameo is "release" an ippool or ip action?

**Comment by sameo** [comment]
@tpepper one would assign an IP from a pool to an instance, and release an IP from from an instance back to a pool. So I guess it would be an ip action.

**Comment by jorgevgut** [comment]
@kaccardi as a user I would think that the usage of floating IPs would help determine costs (I'm assuming public IPs could be expensive). Also the admin could know which tenants are making use of the total quota of IP. Perhaps knowing that a particular tenant (of many that an admin may own) is using more resource could be helpful to track and monitor the cluster.
These are some use cases I can imagine at the moment.

**Comment by tpepper** [comment]
@kaccardi & @jorgevgut it makes sense to me also that a public IP is a potentially scarce and billable resource.  Would tracking a bucket that is "public IP usage hours" and "current public IPs in use" be so hard?

**Comment by kaccardi** [comment]
@mcastelino if a non privileged user does a pools list, what should they be able to see? presumably a list of all pools we deem they can see. And what information is available as far as free/busy ips? Should we give them the actual number of free IPs (and not show busy?), or the percentage of free ips for the pool (for example, pool is 80% allocated or something)?

**Comment by mcastelino** [comment]
@kaccardi I do not think the user should ever be able to see the pool contents in any form. As the pools are data center managed resources today.

**Comment by kaccardi** [comment]
this support was merged.
