### ISSUE TITLE
Swagger builds in travis should not go get ciao

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#559]
Currently, the swagger part of the travis builds in ciao do this

```
   - go list ./... | sed -e "s/github\.com\/01org\/ciao\/vendor\///" | xargs go get
```

i.e., they download the latest version all of ciao's dependencies into the GOPATH.

The problem is that this is not guaranteed to work.  Any build failure upstream in any of ciao's dependencies will break the ciao build, even though ciao itself does build, as it uses the vendored  packages.  The reason we do this go get is because the github.com/yvasiyarov/swagger package does not correctly handle vendoring.  We need to either fix this package or switch to another swagger package that does handle vendoring.

I've seen ciao builds fail from time to time because of this so it needs to be fixed.

**Comment by leoswaldo** [comment]
I'd prefer to send the fix for that, later today I'll be sending the PR to the https://github.com/yvasiyarov/swagger , once the PR is merged I'll update our travis

**Comment by markdryan** [comment]
Will your fix be using go list?

**Comment by leoswaldo** [comment]
no, I'm fixing swagger to use vendoring dir as it should, so we remove the go list ... line

**Comment by leoswaldo** [comment]
PR sent to fix swagger tool to use vendoring dir:

https://github.com/yvasiyarov/swagger/pull/120

I only need confirmation of the merge to send the changes to our travis tool. 
The new change will be to remove the line

 `- go list ./... | sed -e "s/github\.com\/01org\/ciao\/vendor\///" | xargs go get`

and specify our vendor diretory to be used.

**Comment by markdryan** [comment]
@leoswaldo Are there any alternative swagger packages that we can use that don't need to be patched?

**Comment by leoswaldo** [comment]
Updated swagger PR to add native support of vendoring
