### ISSUE TITLE
Add testing for ciao-storage (ceph) via BAT

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#569]
requires ceph support to test the ceph driver.

**Comment by rbradford** [comment]
I discussed this with @markdryan today and we decided it would be best to move this to being a test inside the BAT infrastructure so that it would a.) run on release cluster / b.) could run under singleVM c.)  not need to worry about getting ceph working on travis

**Comment by kaccardi** [comment]
@rbradford ok. you can modify the title to reflect the work that will be done.
