### ISSUE TITLE
ciao-cli: error reports contain unhelpful line numbers

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#595]
because ciao-cli wraps all errors in a wrapper, when go spits out line number information, all you get is the line number of the wrapper. As a developer who isn't familiar with where all the error messages are, I find this not helpful. I'd like the actual line number of the error spit out so I can easily go to that part of the code and see what the problem is.

**Comment by tpepper** [comment]
From IRC:

```
(09:27:57 AM) tcpepper: our logging is a mishmash that's still evolving towards a coherent entity that helps point at the code in question
(09:28:12 AM) kristenc: tcpepper, I marked it as a bug because it was annoying me to death as I try to debug.
(09:28:20 AM) tcpepper: yeah I've hit that too
(09:28:31 AM) kristenc: I considered it a bug that I was having such a hard time due to this.
(09:28:49 AM) markusry: It logger should be using glog.InfoDepth(2, ...)
(09:28:51 AM) tcpepper: developer usability bug for sure
(09:28:54 AM) markusry: The logger I mean
(09:28:57 AM) markusry: ssntp has the same problem
```

**Comment by markdryan** [comment]
See https://github.com/01org/ciao/blob/master/ciao-launcher/qemu.go#L53 for an example.
