### ISSUE TITLE
The START payload can only contain one volume

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#606]
Right now the we can only specify one ceph volume to be attached to an instance at start time, which seems a little restrictive as you can Attach as many volumes as you like at runtime.  It also means that if you boot from volume you cannot attach a second ceph data volume to that instance at creation time.

We should be able to do something like

```
start:
  ... 
  storage:
    -  id: 67d86208-000-4465-9018-fe14087d415f
        boot: true
    -  id: 67d86208-111-4465-9018-fe14087d415f
        boot: false
```

**Comment by tpepper** [comment]
In order to support the OpenStack block-device-mapping-v2 as per issues #387 and #373 I need this to be a list of StorageResources objects, not just one StorageResources object.

**Comment by rbradford** [comment]
```
	// Storage contains all the information required to attach or boot
	// from storage for the new instance.
	Storage []StorageResource `yaml:"storage,omitempty"`
```

Looks fixed!
