### ISSUE TITLE
ciao-cli tenant list returns an error if there are more than two projects

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#609]
This doesn't look correct to me.  I don't understand why I'm getting an error here.  Why should I need to specify a tenant when listing tenants?

```
ciao-cli tenant list
Available projects for admin:
     Project[1]: admin (3e4fb4bc72fc470ebf3d09becebb9992)
     Project[2]: service (5aec402434c74089b0caefc907435817)
F0928 16:59:48.650099   17356 main.go:121] ciao-cli FATAL: Please specify a project to use with -tenant-name or -tenant-id
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x8f6b00, 0xc400000000, 0x7b, 0xac)
    /home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x8da7a0, 0xc400000003, 0xc4202bcd80, 0x8b53c5, 0x7, 0x79, 0x0)
    /home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printf(0x8da7a0, 0xc400000003, 0xc42038a4b0, 0x4f, 0x0, 0x0, 0x0)
    /home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/01org/ciao/vendor/github.com/golang/glog.Fatalf(0xc42038a4b0, 0x4f, 0x0, 0x0, 0x0)
    /home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1148 +0x67
main.fatalf(0xc420310480, 0x3f, 0x0, 0x0, 0x0)
    /home/markus/go/src/github.com/01org/ciao/ciao-cli/main.go:121 +0x94
main.main()
    /home/markus/go/src/github.com/01org/ciao/ciao-cli/main.go:346 +0x5d7
```

**Comment by albertomurillo** [comment]
different tenants could have different permissions, for example the admin user on the admin tenant should be able to list all of the projects in existence.

But a demo user from demo tenant should not be aware of other tenants he doesn't belong to.

**Comment by markdryan** [comment]
I guess I should have clarified, but when I encountered this error I had set

CIAO_USERNAME=admin

From your comments, I don't think I should see this error when I'm an admin. Do you agree?

**Comment by albertomurillo** [comment]
'admin' is just an username, which needs a password and a tenant to be authenticated.
I will review whats the behaviour in openstack when the tenant is not specified.

**Comment by kaccardi** [comment]
It would be worth checking to see if this error is occurring due to how the keystone service is setup with ansible, or if the problem occurs on our existing test clusters. Also, the ciao api was moved around last week - perhaps this is a casualty of that effort.

**Comment by markdryan** [comment]
Please note that this error was encountered on a 4 node cluster set up with the ansible scripts.

**Comment by rbradford** [comment]
This won't happen now as that code has been removed by #1410
