### ISSUE TITLE
Launcher should only enable KVM when available

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#613]
Launcher currently always enables kvm when launching a qemu instance.  This prevents it from running inside environments where KVM is not supported, for example, Travis VMs and Virtual BOX on mac osx.  Launcher should detect whether the node on which it runs supports KVM and if it does not, it should disable the following lines in qemu.go

```
params = append(params, "-enable-kvm")
params = append(params, "-cpu", "host")
```

**Comment by markdryan** [comment]
@rbradford Would you be interested in looking at this?

**Comment by mcastelino** [comment]
@markdryan @rbradford that in itself will not be enough.. I checked that the clear cloud image does not work without kvm. So I need to support an alternate CNCI images for Travis testing... I will work on creating an alternate CNCI image for travis

**Comment by tpepper** [comment]
I see this as a hardware resource (VT-enabled) that should be reported up through the admin UI also.  It might be a sign to the cloud operator that a server is misconfigured (eg: bios set to not enable VT).  If we simply allow VM's to alternatively run without hardware acceleration, one might inadvertantly deploy a software-only emulation cloud and have bad performance compared to what is possible.

If it's a reported resource/capability, then we also need to decide if we expose that to workload templates.  A user might tolerate running w/o h/w acceleration or require it.  Billing might vary between the two also.

**Comment by rbradford** [comment]
@tpepper I think we should keep it simple and only support software qemu for testing. Of course we can re-evaluate that in the future but I don't think that complexity should block us making progress on "Single VM"  testing in Travis.

I agree it is definitely valuable to report out that VT is unavailable on compute node but let's track that somewhere else.

To that extent I propose a ciao-launcher command line option --qemu-virtualisation=[software, auto, kvm].

With the default being "kvm". But for single VM we would use "auto" allowing common scripts for both travis and running single VM with a nested kvm setup.

**Comment by markdryan** [comment]
Sounds good to me.  We could even disable this option on non-debug builds as we do with some of the other options, e.g., --with-ui.  Single VM already does a debug build so this option would be enabled in Single VM itself.

**Comment by tpepper** [comment]
I'm good with @rbradford 's proposal
