### ISSUE TITLE
Single VM Dev Env: Use keystone container for identity services

### ISSUE THREAD

**Issue by mcastelino** [01org/ciao#614]
Currently the single VM tests use a fake identity service. As we now have a dockerized keystone instance we should provision and use this keystone in single VM for identity services.

**Comment by markdryan** [comment]
I'll take this one.  I need to do this to fully test ceph inside the Single VM.  Right now ciao-cli can't find the volume service.  It's probably just as easy to enable keystone in Single VM as it is to update the testutils/identity.go file.
