### ISSUE TITLE
deleting instances with volumes attached is buggy

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#643]
Deleting boot from volume instances does not seem to work properly. 
The instance is deleted but an error is reported.  The volume backing
that instance remains after the instance has been deleted and is
reported to be in-use.

**Comment by markdryan** [comment]
This is what I see:

```
$ ciao-cli instance delete --instance 633d4a70-4244-4925-8ba4-0beadeef0348
F1007 11:03:56.579838   26113 instance.go:171] ciao-cli FATAL: Instance deletion failed: 204 No Content

$ ciao-cli volume list
Volume #1
	Name             []
	Size             [0 GB]
	UUID             [fda8f955-e540-456e-a054-347827705aa4]
	Status           [in-use]
	Description      []
```

**Comment by kaccardi** [comment]
the bug here is related to the Status. Status should switch to "available". the volume should remain.

**Comment by kaccardi** [comment]
problem fixed.
