### ISSUE TITLE
Single VM: Fix identity service race

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#649]
There's a race condition in the Single VM setup.sh script.  It starts controller, waits 5 seconds and then tries to read the address of the identity server from the controllers logs.  This slows down the startup of the single vm cluster and it also fails sometimes, notably on travis.  We should maybe pass in the address or port number of the identity service via the single parameter.

**Comment by kaccardi** [comment]
This issue will be solved when #614 is addressed. closing as duplicate.
