### ISSUE TITLE
ciao-image: Add configuration package support

### ISSUE THREAD

**Issue by obedmr** [01org/ciao#650]
In order to enable zero config in ciao-image service, we need to enable the auto-config feature and ssntp certs auto-discovery.

**Comment by tpepper** [comment]
All actors in the ciao cluster internally use roles embedded in certificates.  Actors who log into the ssntp server are passed config information back, which would include the ceph backend's connection info.  Ssntp needs extended to have a storage role for the storage actors to check into the cluster and receive config info back.

**Comment by obedmr** [comment]
Addressed on #807, now that ciao-image is integrated into ciao-controller, it's not required anymore.
