### ISSUE TITLE
Ciao minimal configuration

### ISSUE THREAD

**Issue by sameo** [01org/ciao#66]
## Ciao Minimal Configuration
One of Ciao major goal is to get as close to a zero config cluster as possible. This issue documents how we want to get there.

### Overview
We want the cluster configuration to be as centralized as possible and this central point of configuration is the Ciao scheduler.
All launchers running on the compute and networking nodes should be able to run with zero configuration input by default.
The controller may need additional configuration information for fetching its HTTPS credentials.

### Configuration data
The configuration data is a [YAML payload] (https://github.com/01org/ciao/blob/master/payloads/configure.go)  that is part of 2 SSNTP frames:

1. The [CONNECTED](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L234) status frame: Whenever a SSNTP client successfully connects to the Scheduler it will receive a CONNECTED frame back which payload is the configuration one.
2. The [CONFIGURE] (https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L213) command frame: Whenever a SSNTP client wants to update part of the cluster configuration it is allowed to send a [CONFIGURE](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L213) command to the Scheduler. It is up to the Scheduler to decide if the sender is allowed to update the cluster overall configuration or not. Typically we should only allow Controller to update this piece of information.

The configuration payload currently contains the following piece of information: 

* The identity service type (e.g. `Keystone`) and its URL 
* The image service type (e.g. `Glance`) and its URL
* Configuration data for the controller:
  * The compute API configuration data:
     * The compute API port
     * The compute API certificates
  * The identity configuration data:
    * The identity credentials
* Configuration data for the launchers:
   * The cluster management network
   * The cluster compute network
   * The disk limit flag
   * The memory limit flag

### Configuration updates
Both clients and servers can propagate cluster configuration updates by sending a [CONFIGURE](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L213) command.
The Scheduler will be responsible for forwarding all valid configuration changes to all clients (Controller, Agents).

As the central configuration point, the Scheduler is also responsible for updating the stored configuration data. The storage back end details are implementation specific.

### Scheduler
The Scheduler is Ciao's main configuration point and as such is responsible for:
* Propagating the latest configuration data through the [CONNECTED](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L234) status frames it sends back to connected clients.
* Forwarding [CONFIGURE](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L213) commands to all interested clients.
* Storing configuration changes that it receives through a [CONFIGURE](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L213) or that it initiated. Configuration storage details will be implemented in the Ciao config package.
* Validating cluster configuration change requests sent by clients (typically the controller). The scheduler will send an [InvalidConfiguration error](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go) back to the client if the configuration payload is invalid and obviously will not store an invalid configuration.

### Launcher
Launchers build their configuration from 2 main data sources:
1. Their CA certificate. This is a [Ciao specific certificate](https://github.com/01org/ciao/tree/master/ssntp/ciao-cert) an it should contain the Scheduler URL (URI or IP). A launcher uses that information to implicitly know where to connect to.
2. The [CONNECTED] (https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L234) status payload that contains a [configuration payload] (https://github.com/01org/ciao/blob/master/payloads/configure.go) built by the Scheduler from its configuration data.

### Controller
The Ciao Controller also builds its configuration from the 2 same data sources as Launchers.

### Ciao config package
The Ciao config package main purpose is to fetch configuration data from a given storage back end and build a [configure YAML payload](https://github.com/01org/ciao/blob/master/payloads/configure.go) from it.
More precisely this package should provide the following features:
* Efficiently build a configure YAML payload from the Ciao configuration back end.
* Update the Ciao configuration back end based on received [CONFIGURE](https://github.com/01org/ciao/blob/master/ssntp/ssntp.go#L213) payloads.
* Transparent storage back end support (etcd, filesystem, db, etc...).

**Comment by markdryan** [comment]
From a launcher point of view the main change will be that we will need to delay network initialisation until we receive the configuration payload.

This is doable but will require some re-work of launcher's initialisation code.  Right now we initialise networking before calling ssntp.Dial.

Some questions/thoughts:

1. It's not clear to me what this means for networking.  Let's say launcher starts, receives a configuration payload, creates some instances, exits, restarts and then receives a new configuration payload.  Is it possible for the management and compute net address to differ between the first and second payloads?  If so what are the implication for existing instances and their bridges?  Do we need to destroy and re-create their vnics?  I'm not sure this can be done for docker instances.
3. How should launcher return an error if the configuration information is invalid.  For example, if the management network is wrong and libssnet.ComputeNode.Init() fails?
4. It's not clear to me how launcher gets the configuration information.  Will this be returned by Dial?  Will it be passed in ConnectNotify?

**Comment by markdryan** [comment]
Also, we need to consider how the cnci-agent will be affected by this.  Will this be auto configured as well?

Note it occurs to me that if the IP address of the scheduler is in the certificate we could remove the ciao.iso image currently uses to pass the scheduler's address from launcher to the cnci_agent.

**Comment by markdryan** [comment]
> It's not clear to me how launcher gets the configuration information. Will this be returned by Dial? Will it be passed in ConnectNotify?

Okay, I see now.  I hadn't synced the latest version of the code.  launcher should call ClusterConfiguration() after Dial returns.  Is that correct?

**Comment by sameo** [comment]
My responses to your questions:

1 and 2) This is a problem we already have today if the command line options are invalid. I guess we should add an error type for that purpose so that both scheduler and the controller would be notified.
I really don't expect networking parameters to change when the cluster is running, as it would basically mean that we'd have to stop and restart all running instances.
The idea here is for the scheduler (or the controller, to be discussed) to decide if a configuration change is allowed/valid or not. Here as well, we'll have to add a new error type for that.

3) So this is a WIP: I have added a ClusterConfiguration() asynchronous call to get the latest cluster configuration data at any point in time. Typically you would call it after client.Dial() succeeded.
I could leave it that way and let all client implementations handle the CONFIGURE command from their command notifier but I think I'm going to add a specific configure notifier to explicitly force client implementations to handle that command.
Also, a question for you: Would it be more convenient to have Dial() return the configuration payload ?

**Comment by markdryan** [comment]
> Also, a question for you: Would it be more convenient to have Dial() return the configuration payload ?

From launcher's point of view, at least from the point of view of the current implementation, returning the configuration information from dial or being able to retrieve it via ClusterConfiguration will require less changes than retrieving the information from CommandNotify.

If we want to be able to update a launcher instance after it had connected to the server I guess we'll need the command notifier as well.  Perhaps, we'd ignore the network settings in the CommandNotify handler though.  Note I say as well here, i.e., it would be easier for launcher if it could receive the initial configuration from Dial or from ClusterConfiguration.

One of the nice things about doing the network initialisation after the call to Dial returns is that we can send an error if it fails.  Right now, launcher exits before connecting to the scheduler if networking fails, and so controller and scheduler get no information about that node.

**Comment by sameo** [comment]
@markdryan I'll leave the ClusterConfiguration() call for now as I'm not excited about breaking the Dial() API unless there's a strong need for it.
For after-launch updates, I am thinking about adding a specific notifier (ConfigureNotify()) to the SSNTP client interface so that clients are forced to at least thinking about handling it. They can have a no-op notifier if they don't care.

**Comment by obedmr** [comment]
@sameo I have a question regarding a couple of variables in controller configure struct: 
What would be reason of using ComputeCACert and ComputeCert:
https://github.com/01org/ciao/blob/master/payloads/configure.go#L72-73

As far I understand, those certs would be located in a local path. Is it necessary to pass it by CONFIGURE payload?

**Comment by sameo** [comment]
@obedmr The reason for `ComputeCACert` and `ComputeCert` to be in the CONFIGURE payload is for avoiding to pass `--httpscert` and --httpskey` to `ciao-controller` when starting it.
Even if those files are local to the controller, we still need to tell it where they are.

**Comment by obedmr** [comment]
Thanks @sameo  for the clarification. I was thinking that it referred to the SSNTP certificates. Now, it's clear, don't you think that we may change those name to something like HTTPCert and HTTPKey? to avoid confusion with the following options:
```
-cacert string
        CA certificate (default "/etc/pki/ciao/CAcert-server-localhost.pem")
-cert string
        Client certificate (default "/etc/pki/ciao/cert-client-localhost.pem")
```

**Comment by sameo** [comment]
@obedmr Yes, I agree it would make more sense. Also we may use the controller HTTPS endpoints for more than the compute API, so we should call it HTTPCACert and HTTPKey.

**Comment by mrkz** [comment]
This Issue works as documentation for the **zero config** approach which is part implemented by the 'file' back-end  (already merged in [Pull Request 149](https://github.com/01org/ciao/pull/149)), missing the etcd and ZooKeper back-ends which are now tracked separately in #399 and #400 respectively. Given the previous tracking, this Issue can be closed now.
