### ISSUE TITLE
ciao-controller: complete volume create asynchronously

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#673]
While we currently do allow the instance to start asynchronously, we do not return status back to the http request until after we've sent all the start workload requests. When creating disk volumes with workload start (especially in bulk) this can lead to a very long delay before returning the http response. It'd be nicer to send the status for the pending command even if it hasn't made it out of the controlller. We can handle any failures by updating the status after the fact the same way we do when launcher fails.

**Comment by kaccardi** [comment]
please put any asynchronous failure information into the event log.

**Comment by tpepper** [comment]
This could be optional.  Our current initial crude implementation's performance makes this in-between waiting annoying for the user.  If we've addressed that slow-to-create by removing the image conversion, this isn't needed so much.

**Comment by kaccardi** [comment]
I'm going to close it for now since we think we might not need it with the redesign. We can reassess the situation after the merge.
