### ISSUE TITLE
ciao-controller: should not ask launcher to create invalid configurations

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#675]
Controller should do some validation on the configuration it sends to launcher. In particular it should check that if image_uuid is empty then there must be a valid volume to use.

**Comment by tpepper** [comment]
A portion of this (eg: volume exists) is in PR #700 

The broader validation of user-input workload is tracked in a separate ticket issue #244

**Comment by rbradford** [comment]
Closing as duped in the broader #244
