### ISSUE TITLE
Who mounts cephfs and how do they do it?

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#679]
Who is supposed to mount cephfs over /var/lib/ciao/images.  Is the intention that this be done by the admins who install ciao, via ansible for example, or should the ciao components do this, assuming they have the permissions to do so?  Also should we use fuse or the kernel client to mount the volume?

**Comment by rbradford** [comment]
Is cephfs a hard dependency of ciao? Images could be be downloaded from the image service rather than shared via a network filesystem.

**Comment by tpepper** [comment]
Our decision was to initially do a tight default integration with cephfs, to make things easier for an operation in a small initial deployment and for us to debug (eg: "ls" on the fs shows you what's there).

I'm imagining systemd unit files for ciao components, which articulate that they run after a mount unit runs for /var/lib/ciao/images.  The server / storage cluster would be presumed to be running and managed in production (ie: distinct from us needing to do it if/when we're in test automation rolling a cluster on the fly).

I don't know of any specific benefits for us in using the fuse or kernel mount path.

**Comment by tpepper** [comment]
On the choice of fuse vs kernel, at some point we should look at performance analysis, as per eg:
https://www.spinics.net/lists/ceph-devel/msg32876.html

**Comment by rbradford** [comment]
Closing as we decided not to use cephfs and instead have ceph rbd as our requirement.
