### ISSUE TITLE
ciao-image ignores most of the parameters passed to by ciao-cli image add

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#681]
If you look at the help for ciao-cli image add you will see that it takes a whole pile of parameters.  However, the majority of these are simply ignored by the image service.  We should do something with them.

**Comment by markdryan** [comment]
Of all the fields in the image.CreateImageRequest

```
Name            string
ID              string
Visibility      Visibility
Tags            []string
ContainerFormat ContainerFormat
DiskFormat      DiskFormat
MinDisk         int
MinRAM          int
Protected       bool
Properties      interface{}
```

Only Name and ID are used by ciao-image.

**Comment by rbradford** [comment]
What parameters are we going to remove?

**Comment by obedmr** [comment]
@rbradford if we want compatibility with OpenStack image service (Glance), I'd recommend to keep all of them and set some default values for those we're not using yet. Those unused parameter could be useful in the future. What do you think @rbradford  @kaccardi @markdryan

**Comment by rbradford** [comment]
We can still maintain compatibility with openstack tools but we don't need to expose them in our tools.

**Comment by obedmr** [comment]
@rbradford, which ones you're proposing to remove?

**Comment by obedmr** [comment]
Assigning to @rbradford who is actually doing the PR.
