### ISSUE TITLE
ciao-cli image list on SingleVM has some empty values

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#684]
Taken from a run on SingleVM. I would expect values such as size/checksum/status at the least to be filled in.

```
$ ciao-cli image list
Image #1
    Name             [Fedorda Cloud Base 24-1.2]
    Size             [0 bytes]
    UUID             [73a86d7e-93c0-480e-9c41-ab42f69b7799]
    Status           [queued]
    Owner            []
    Disk format      []
    Container format []
    Minimal disk     [0 GB]
    Minimal memory   [0 MB]
    Checksum         []
    Visibility       [public]
    Protected        [false]
    CreatedDate      [2016-10-14T15:58:10.241691884+01:00]
    LastUpdate       []
    Tags             [[]]
    File             [/v2/images/73a86d7e-93c0-480e-9c41-ab42f69b7799/file]
    Schema           [/v2/schemas/image]

```

This might be related to #632 but there might also need to be changes elsewhere.

**Comment by tpepper** [comment]
dumpImage(i *images.Image) in ciao-cli/image.go needs reviewed.  Some of the fields have no meaning in Ciao, versus in OpenStack.  The lines of code that currently fmt.Printf()'ing those fields simply need removed.

Relates also to issue #681 which enables the user to get data into the fields in the first place.

**Comment by rbradford** [comment]
I think we should only show the fields where we have useful data. We can expose 
more if we start to use those fields

Giving the following:
```
     Name             [Fedorda Cloud Base 24-1.2]
     Size                [<Fill in from rbd>]
     UUID              [73a86d7e-93c0-480e-9c41-ab42f69b7799]
     Status            [queued]
     CreatedDate      [2016-10-14T15:58:10.241691884+01:00]
```

Which seems a bit more reasonable.
