### ISSUE TITLE
end-user workload definition

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#694]
Our initial implementation had some compromises to get things moving which made for a more developer/development focused system.  Today to define a workload, you need to have root priv's on the node running ciao-controller and edit .csv files.  Tenants need a means to define workloads through ciao-cli.

NOTE: This is distinct from issue #510, which is about insuring there is tenant separation of defined workloads throughout the ciao stack.  And there's no point implementing issue #244 (workload validator) until we have this ticket (workload definition) implemented.

**Comment by kaccardi** [comment]
@tpepper I'm going to break this up into multiple issues to make it easier to track progress using waffle/github project
