### ISSUE TITLE
Change ciao-controller IP allocation algorithm to re-enable overlapping IP

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#712]

**Comment by kaccardi** [comment]
Our algorithm for allocating network IP addresses in controller currently does not allow tenants to have overlapping IP addresses. Adjust the algorithm to allow the ips to overlap.

**Comment by kaccardi** [comment]
https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/datastore.go#L621 (AllocateTenantIP). There are several comments in the code about preventing overlap. The algorithm reserves a subnet by using a map of subnet to boolean to indicate globally whether a subnet is in use. You should remove the map ds.allSubnets[int(i)]. The tenant should have unique IPs, but it's ok to have duplicate IPs in another tenant.

**Comment by mrkz** [comment]
A couple of questions here:

Is this just for internal networks? (no external IP related)
What would be an example of what's being done at the moment vs what would be the desired output?

To reproduce this likely would need to launch workloads with different tenants, is that correct?

**Comment by kaccardi** [comment]
@mrkz yes - the instance IPs are the same as internal IPs.

You can use singleVM to do your development however, until PR #813 is merged, you can't test with singleVM since you need 2 tenants and singleVM only has one.
 
to test - you can launch a workload for 2 different tenants. You should observe the internal IPs that are assigned to them (use ciao-cli instance list per tenant). You will see for example, the first one you launched will have an instance IP of 172.16.0.2, and the one for the second tenant has 172.16.0.3. After your code is complete, what you should expect to see is that one instance launched in one tenant will have an IP allocated as 172.16.0.2 and another instance launched in a different tenant also has 172.16.0.2. Instance IPs should be unique within a tenant, but can be duplicated in another tenant.

**Comment by kaccardi** [comment]
@mrkz when you are code complete in controller and have tested manually, please also add a BAT test to script a test for this so we can verify it automatically on each release.

**Comment by kaccardi** [comment]
@mcastelino says that this should be valid, and if you have any problems at all with the networking not working after this change it's a bug in the networking code and he'll fix it. So, if you wind up with problems, you can file an issue or just ping him directly.
