### ISSUE TITLE
Modification to keystone config to add k8s project

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#722]
keystone will need to have a "kubernetes" project configured by default. ciao user should have admin role in this project. add an example user to have a role of user in this project.

**Comment by mrkz** [comment]
This sounds more a 'deployment' issue/feature rather than a configuration one.

@obedmr , @albertomurillo  what do you think about it?

**Comment by albertomurillo** [comment]
@mrkz keystone projects are created in ansible scripts as well as singlevm scripts.

**Comment by mrkz** [comment]
@albertomurillo yes, that's precisely why sounds more like a 'deployment' task to me

**Comment by mrkz** [comment]
Changing the 'configuration' label to 'ciao-deployment' as this task is not related to the configuration component

**Comment by kaccardi** [comment]
we changed our k8s strategy, so this is no longer relevant.
