### ISSUE TITLE
revendor gophercloud to new project location

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#724]
gophercloud has moved:
https://github.com/gophercloud/gophercloud

**Comment by markdryan** [comment]
I tried but there are problems with the latest version of gophercloud that prevent us from updating.  All the issues are related to the way times are parsed in responses gophercloud receives from the controller.  If we revendor right now we'll break ciao-cli's image and volume commands.

There is a PR pending that will fix most of these issues

https://github.com/gophercloud/gophercloud/pull/190

but it has been dormant for 6 weeks.  I've posted some comments on the PR asking when it will be merged.

**Comment by markdryan** [comment]
gophercloud/gophercloud#190 has now been merged but I think there will still be some issues related to Volume timestamps.  I'll have a quick this and if necessary submit a PR to gophercloud.

**Comment by markdryan** [comment]
I've submitted a bug

https://github.com/gophercloud/gophercloud/issues/248

and a PR to gophercloud

https://github.com/gophercloud/gophercloud/pull/249

There's a whole pile of other changes needed to the ciao-source code to work with the new version of gophercloud.  I've committed these to a branch.

https://github.com/markdryan/ciao/tree/fix-724
