### ISSUE TITLE
create ciao identity interface for project creation/deletion/update

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#729]
ciao will need to be able to create new projects in our identity service. This generic interface should not require knowledge of keystone from the caller. To implement the interface, we would want to provide a keystone implementation for it. Normally we'd use gophercloud for this, but gophercloud does not currently have support for the identity v3 api for projects. This support will need to be added to gophercloud or provided outside of gophercloud.

**Comment by tpepper** [comment]
With https://github.com/gophercloud/gophercloud/issues/157 by way of re-vendoring gophercloud into ciao, we have the basis to create an abstracted go interface in ciao with keystone, mock, or other implementation backends.

**Comment by kaccardi** [comment]
we changed our k8s strategy, so this is no longer relevant.
