### ISSUE TITLE
Controller should sort instances (and maybe other lists as well)

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#74]
When the ciao-cli or ciao-webui want to retrieve a list of instances they use the "/v2.1/{tenant}/servers/detail endpoint.  The order of the instances returned seems to be random.  You can see this easily by simply doing

./ciao-cli -list-instances

each time you run this command the list of instances returned is different.  This is troublesome for the UI as it means the table of instances changes every time the UI refreshes.  With a short refresh rate it makes it almost impossible to navigate through the instances.  As the UI only retrieves a subset of the available instances at any one time it cannot do the sorting.  It needs to be done in controller.

We should probably sort all lists that the controller returns in the same manner.

**Comment by kaccardi** [comment]
hi, yes this is annoying.  sort by instance uuid you think?

**Comment by markdryan** [comment]
Yes, I think so.

**Comment by kaccardi** [comment]
sorting the instances prior to returning them does have a performance impact.

BenchmarkGetAllInstances-8      	          500000	       6413 ns/op
BenchmarkGetAllInstancesSorted-8	  100000	     15038 ns/op

My opinion is that it's acceptable to take this hit here as it's for the UI and the UI refresh rate is such that you'll probably never notice it.

**Comment by kaccardi** [comment]
#82
