### ISSUE TITLE
Subnets returned by the /v2.1/cncis command are prefixed by the string Subnet

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#753]
So what I actually see when I call this API is

```
[]string{
"Subnet 172.16.0.0/8"
} 
```

Should the Subnet string be there?

Any scripts that need to retrieve this information would need to remove the preceeding Subnet string.

**Comment by kaccardi** [comment]
https://github.com/01org/ciao/wiki/Compute-API#api-v21cncis-get

**Comment by markdryan** [comment]
Swagger documentation of this function does not mention the CNCI Geography.

**Comment by kaccardi** [comment]
ok to fix this per webui team.

**Comment by rbradford** [comment]
I just checked this out and I can't reproduce it any longer.
