### ISSUE TITLE
VM booting should always have workload storage associated with it

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#758]
Currently there are two different ways to boot a VM from an image:

a.) using workload storage information which will create a volume from the image and boot from that
b.) using an image that is assumed to be on the individual compute node (using the information in the base workload)

We should phase out b.) and always mandate that storage is specified in the workload.

**Comment by tpepper** [comment]
An additional variant:

c.) using a pre-existing image that is specified by -volume on the cial-cli instance add command line

In this case the VM boots without workload storage defined, but with instance specific storage defined.  This will be enabled with resolution of issues #387 and #373 .

**Comment by rbradford** [comment]
In PR #811 I updated all the reference workload .csv files to have storage for all VM workloads.
