### ISSUE TITLE
ciao-image has almost no logs

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#779]
There are a few logs written if the service fails to start but apart from that there's nothing.  This makes it a little hard to debug problems.

**Comment by markdryan** [comment]
Also, the logs should be written to /var/lib/ciao/logs by default.

**Comment by albertomurillo** [comment]
ciao-image is not looging what ceph commands is running underneath

**Comment by obedmr** [comment]
WIP, this week I'm focusing in adding more logs.
