### ISSUE TITLE
configuration: There is no universal way to get cluster configuration

### ISSUE THREAD

**Issue by albertomurillo** [01org/ciao#787]
ciao-controller implements its own newSSNTPClient() function
to read the cluster configuration while ciao-launcher has
its own loadClusterConfig()

This is becoming messy since there is no universal way
to get cluster configuration for new services (i.e. ciao-image)

**Comment by mrkz** [comment]
@albertomurillo so further reading on the ciao-launcher and the ciao-controller code (both are SSNTP clients), both are using the client.ClusterConfiguration function from the ssntp client API.

What is also true is that the abstraction of how they manage to call this function of the ssntp.client.ClusterConfiguration is different.
ciao-controller uses directly a [ssntpClient struct](https://github.com/01org/ciao/blob/dc1bc769d429bd48f9c41d9ef73b651c676f4b67/ciao-controller/client.go#L48) to manage it's role as SSNTP client.
ciao-launcher abstracts this using an [interface](https://github.com/01org/ciao/blob/dc1bc769d429bd48f9c41d9ef73b651c676f4b67/ciao-launcher/ssntp.go#L37) which is satisfied by the [ssntpCon](https://github.com/01org/ciao/blob/dc1bc769d429bd48f9c41d9ef73b651c676f4b67/ciao-launcher/ssntp.go#L53) struct, which has a ssntp.Client embbeded field)

So at the end of the day, both are using the required ssntp client call to get the cluster configuration and both satisfy the `ssntp.ClientNotifier` interface (required for all SSNTP clients).

also, the SSNTP client implementation requires that all clients implement the `ssntp.ClientNotifier` interface, which may be the reason for this to be abstracted differently.

If this should be refactored for both ciao-controller and ciao-launcher to be abstracted the same way, this is a decision I'll leave for each [component owner](https://github.com/01org/ciao/wiki/Package-maintainers) to take.

**Comment by markdryan** [comment]
For the record, the reason for the abstraction in launcher is for the unit tests.  Having the abstraction in place allows us to completely fake the connection to the scheduler.  We can then test without any certificates and also generate unusual sequence of ssntp events/commands.
