### ISSUE TITLE
ciao-cli node list -compute returns error

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [01org/ciao#806]
After install ciao in a 4 nucs cluster from the configuration created at "(pwd)/clear-config-management/examples/ciao" (not using the container), ansible reply success, but after source the generated files "admin-ciaorc" and "openrc" when trying to list he nodes, got this error

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # source admin-ciaorc 

root@controller.example.com ~/cloud/clear-config-management/examples/ciao # source openrc 

root@controller.example.com ~/cloud/clear-config-management/examples/ciao # ciao-cli node list -compute
E1109 23:38:13.002075   30742 authenticate.go:43] ciao-cli ERROR: Could not get AuthenticatedClient Post https://controller.example.com:35357/v3/auth/tokens: dial tcp 10.64.153.159:35357: getsockopt: connection refused
E1109 23:38:13.002345   30742 identity.go:126] ciao-cli ERROR: Failed to create an AuthenticatedClient
E1109 23:38:13.154504   30742 main.go:220] ciao-cli ERROR: Could not send HTTP request Get https://controller.example.com:8774/v2.1/nodes: dial tcp 10.64.153.159:8774: getsockopt: connection refused
F1109 23:38:13.154541   30742 node.go:123] ciao-cli FATAL: Get https://controller.example.com:8774/v2.1/nodes: dial tcp 10.64.153.159:8774: getsockopt: connection refused
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x8feb00, 0xc400000000, 0xa6, 0x124)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x8e2820, 0xc400000003, 0xc4200d20c0, 0x8bd491, 0x7, 0x7b, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x8e2820, 0xc400000003, 0x1, 0xc4200e9b68, 0x1, 0x1)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc4200e9b68, 0x1, 0x1)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc420056ee0, 0x6a, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/main.go:127 +0x126
main.listComputeNodes(0x0, 0x9, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/node.go:123 +0x9dc
main.(*nodeListCommand).run(0xc420018600, 0xc42000c2b0, 0x0, 0x0, 0xc42000c2b0, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/node.go:107 +0xdb
main.(*command).run(0x8e0de8, 0xc42000c2b0, 0x0, 0x0, 0xc42008d868, 0x0)
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/main.go:55 +0x15b
main.main()
	/builddir/build/BUILD/ciao-62/src/github.com/01org/ciao/ciao-cli/main.go:401 +0xf7
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # 
` 

here is the "admin-ciaorc" file

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # cat admin-ciaorc 
export CIAO_CONTROLLER=controller.example.com
export CIAO_IDENTITY=https://controller.example.com:35357
export CIAO_USERNAME=admin
export CIAO_PASSWORD=adminUserPassword
export CIAO_TENANT_NAME=admin

`

here is the "openrc" file

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # cat openrc 

export OS_PROJECT_DOMAIN_ID=default
export OS_USER_DOMAIN_ID=default
export OS_PROJECT_NAME=admin
export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=adminUserPassword
export OS_AUTH_URL=https://controller.example.com:35357/v3
export OS_CACERT=certificates/keystone/keystone_cert.pem
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
`

**Comment by markdryan** [comment]
It looks like keystone is not running.  Could you ssh onto the controller.example.com node and do a sudo docker ps -a

Are you running ceph on your cluster as well?  We did encounter an issue before in which there was a port conflict between ceph and keystone.

**Comment by arturo-garcia-garcia** [comment]
Hi @markdryan , answering your questions, here is the output of the docker command

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # sudo docker ps -a

CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                                        NAMES
6a76371d2c45        clearlinux/ciao-webui   "/bin/sh -c '/usr/bin"   15 hours ago        Up 15 hours         0.0.0.0:443->443/tcp                                         ciao-webui
aed4a2a3fbd0        clearlinux/keystone     "/bin/sh -c '/usr/bin"   15 hours ago        Up 15 hours         0.0.0.0:5000->5000/tcp, 3306/tcp, 0.0.0.0:35357->35357/tcp   ciao-keystone
`
Next, yes, I have a ceph running in the cluster too

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # ceph -s

    cluster d1582c6e-d866-403f-8453-43620eba4702
     health HEALTH_OK
     monmap e1: 1 mons at {controller=192.168.10.10:6789/0}
            election epoch 4, quorum 0 controller
      fsmap e5: 1/1/1 up {0=controller=up:active}
     osdmap e10: 6 osds: 6 up, 6 in
            flags sortbitwise
      pgmap v23: 320 pgs, 3 pools, 2068 bytes data, 20 objects
            30924 MB used, 149 GB / 179 GB avail
                 320 active+clean
`

and keystone seems to be up, since I can list the users after source the "openrc" file

`
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # source openrc 
root@controller.example.com ~/cloud/clear-config-management/examples/ciao # openstack user list

+----------------------------------+-------+
| ID                               | Name  |
+----------------------------------+-------+
| 6ae299a2fbc741d8b2d94f40b9a3782b | demo  |
| bffc418a676e4817b3eaf95158656be4 | ciao  |
| edcfc59f646c4727bb51638548555e7d | admin |
+----------------------------------+-------+
`

**Comment by albertomurillo** [comment]
Also the playbooks from clear-config-management are not being used and will be removed shortly. you should use those from ciao/_DeploymentAndDistroPackaging/ansible

**Comment by arturo-garcia-garcia** [comment]
HI @albertomurillo 
I try install using ciao/_DeploymentAndDistroPackaging/ansible and still receiving the same error

```
root@controller.example.com ~/BAT/cloud # ciao-cli node status
E1130 18:41:37.926971   11417 authenticate.go:43] ciao-cli ERROR: Could not get AuthenticatedClient Post https://controller.example.com:35357/v3/auth/tokens: dial tcp 10.64.153.159:35357: getsockopt: connection refused
E1130 18:41:37.927267   11417 identity.go:126] ciao-cli ERROR: Failed to create an AuthenticatedClient
E1130 18:41:38.036786   11417 main.go:220] ciao-cli ERROR: Could not send HTTP request Get https://controller.example.com:8774/v2.1/nodes/summary: dial tcp 10.64.153.159:8774: getsockopt: connection refused
F1130 18:41:38.036816   11417 node.go:228] ciao-cli FATAL: Get https://controller.example.com:8774/v2.1/nodes/summary: dial tcp 10.64.153.159:8774: getsockopt: connection refused
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x901c00, 0xc400000000, 0xae, 0x124)
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x8e5860, 0xc400000003, 0xc4200f20c0, 0x8c02f9, 0x7, 0xe4, 0x0)
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x8e5860, 0xc400000003, 0x1, 0xc42010bd40, 0x1, 0x1)
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42010bd40, 0x1, 0x1)
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc420076c80, 0x72, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/ciao-cli/main.go:127 +0x126
main.(*nodeStatusCommand).run(0xc4200f82a0, 0xc4200781c0, 0x0, 0x0, 0xc4200781c0, 0x0)
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/ciao-cli/node.go:228 +0x532
main.(*command).run(0x8e3e30, 0xc4200781c0, 0x0, 0x0, 0xc4200a9bc8, 0x0)
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/ciao-cli/main.go:55 +0x15b
main.main()
	/builddir/build/BUILD/ciao-75/src/github.com/01org/ciao/ciao-cli/main.go:401 +0xf7

```

**Comment by arturo-garcia-garcia** [comment]
After some research with @albertomurillo , it come up that this was a DHCP issue, after update on configuration  to properly resolve the names, ciao-cli is working again, closing this issue
