### ISSUE TITLE
ciao-image, ciao-cli: image download doesn't work

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#809]
For example

```
ciao-cli image download --image 73a86d7e-93c0-480e-9c41-ab42f69b7799
F1110 11:27:28.168507   27505 image.go:329] ciao-cli FATAL: Could not read [http: read on closed response body]
goroutine 1 [running]:
```

It seems that this feature is not implemented in the image service.  We need to decide whether or not we're going to implement this.  If not we should remove the command from ciao-cli.

**Comment by kaccardi** [comment]
this code should be removed from cli until a later date.

**Comment by rbradford** [comment]
This has been removed by 842393fe9e9cb3b75166fc195114863b4de5700f
