### ISSUE TITLE
Should use parameterized SQL queries over fmt.Sprintf 

### ISSUE THREAD

**Issue by gcmurphy** [01org/ciao#81]
Failure to use parameterized SQL queries could lead to SQL injection:

 * https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/sqlite3db.go#L1007
 * https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/sqlite3db.go#L1119
 * https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/sqlite3db.go#L1431
 * https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/sqlite3db.go#L1432
 * https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/sqlite3db.go#L1448
 * https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/sqlite3db.go#L1467
 * https://github.com/01org/ciao/blob/master/ciao-controller/internal/datastore/sqlite3db.go#L1532

Should use a prepared statement of similar instead of fmt.Sprintf here.

**Comment by kaccardi** [comment]
Hi, thanks!  I have created a pull request with the changes to address this issue, I'd appreciate your review. 
#87
