### ISSUE TITLE
ciao-image,ciao-cli: image modify doesn't work

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#810]
For example

```
$ ciao-cli image modify --image df3768da-31f5-4ba6-82f0-127a1a705169
F1110 16:18:01.010684   16332 image.go:547] ciao-cli FATAL: Could not update image's properties [Expected HTTP response code [200] when accessing [PATCH https://singlevm:9292/v2/images/df3768da-31f5-4ba6-82f0-127a1a705169], but got 404 instead
404 page not found
```

It seems that this feature is not implemented in the image service.  We need to decide whether or not we're going to implement this.  If not we should remove the command from ciao-cli.

**Comment by obedmr** [comment]
@markdryan  I spend a few hours tryinng to implement it, I found this functionality is kind of tricky,  because we depend of a PATCH http method which is not straight forward to implement in golang. I agree to decide if we should keep it or remove it from our CLI.

**Comment by kaccardi** [comment]
this code should be removed from cli until a use case is presented for ciao.

**Comment by rbradford** [comment]
This has been removed by 842393fe9e9cb3b75166fc195114863b4de5700f
