### ISSUE TITLE
ansible: change `ciao_guest_key` var to contain the public ssh key

### ISSUE THREAD

**Issue by mrkz** [01org/ciao#814]
the variable `ciao_guest_key` in [_DeploymentAndDistroPackaging/ansible/group_vars/all](https://github.com/01org/ciao/blob/master/_DeploymentAndDistroPackaging/ansible/group_vars/all) should contain the actual public ssh key, instead of the location of the key.

With this change, user would not need to map the public key into the ciao-deploy container, but just paste it as part of the configuration steps of the cluster setup.

**Comment by mrkz** [comment]
the ansible task would change from copying the ssh pubkey to write the content of the variable into a file instead.

**Comment by albertomurillo** [comment]
This is not janitorial since the user does not have instructions to map the public key required to login into the vms launched by ciao to the container.

This means the scripts are using a key in the container that is lost when the container stops.

**Comment by albertomurillo** [comment]
To fix this you can either map the public key require to login into the containers or apply the change proposed above
