### ISSUE TITLE
ansible: replace ciao-compute and ciao-network with ciao-launcher role

### ISSUE THREAD

**Issue by albertomurillo** [01org/ciao#819]
There is no need to have separate roles for ciao-compute and ciao-network since both are
starting the same binary. The role gets determined by the certificate

**Comment by tpepper** [comment]
If the ansible scripting will do any node prerequisite software install/setup (versus osprepare in the binary), then we should keep two roles.  The network nodes only run VM appliances, not containers.  This means no need to install all of the container management system dependencies on those nodes and decreases the security attack surface of those nodes.

**Comment by albertomurillo** [comment]
ciao-launcher role would have a way to differentiate between a network node and a controller node either with a variable or checking if the host is under [computes] or [networks] group in the inventory file.
