### ISSUE TITLE
document required host/role firewall rules

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#822]
If deployed on hosts with restrictive firewall rules, Ciao is unable to operate.  The Ciao deployment documentation needs to express what ports/protocols are needed per Ciao server host/role type (eg: identity, storage, controller, scheduler, compute node, network node, etc.).

@mcastelino has mentioned that at least the networking node is likely going to need its iptables fully delegated to Ciao.

This also impacts singlemachine/singleVM.

Especially on Fedora the default firewall rules are liable to be restrictive.  But also on a well run cluster, IT security is likely to desire strong controls with only well established ports/protocols exposed.

**Comment by mcastelino** [comment]
@tpepper to expand on this, on CN and NN's the Firewall rules have to be setup such that
- All tenant expressed per workload restrictions are enforced
- All Data Center required firewall rules are enforced
In case of conflicts between Data Center firewall rules and Tenant firewall rules, the data center rules should take precedence. It will be hard to have two agents managing the firewall rules in the case of CN and NN.

On the control nodes, we can support allowing the data center operator to setup the system with any firewall settings and ciao can add ciao specific exceptions.

**Comment by obedmr** [comment]
@erick0z could you take a look on this.
