### ISSUE TITLE
travis: gocyclo on unit test .go files?

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#825]
does it makes sense to have gocyclo run on travis on our _test.go files?

**Comment by markdryan** [comment]
@kaccardi We already do.

The only exception I can see here is the BAT tests.  As these tests are in a folder ignored by the go build system their currently ignored.  I'll update travis to check these files as well.

Have you come across some other test files that are not covered by static analysis.

**Comment by kaccardi** [comment]
@markdryan my question was poorly worded. I noticed that we *do* run gocyclo on our unit tests and it made me wonder if we *should not* do this. I wondered if we were making things hard on ourselves without much benefit.

**Comment by kaccardi** [comment]
it was decided that I should quit whining and deal with it.
