### ISSUE TITLE
ciao-cert: do certs need subjectAltName

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#843]
https://github.com/01org/ciao/issues/826 indicates that https://tools.ietf.org/html/rfc2818 modifies how name lookups are handled to mitigate potential man in the middle attacks.  The ciao-cert tool creates certificates with dNSName specified, but no subjectAltName or Common Name.  Is that ok as of RFC2818 or does an subjectAltName need added in the ciao-cert certificate creator?

**Comment by tpepper** [comment]
@sameo what's your read of RFC2818 relative to how you originally set up the Ciao cluster certs?

**Comment by sameo** [comment]
@tpepper By default we ciao-cert creates certs with SAN. We translate the --host entries into a DNSName list for SAN and the --ip one into an IPAddress list.

If you run e.g.
```
ciao-cert --host example.com,foo.example.com --ip 10.1.1.10,192.168.0.10 -server
```

And then:

```
openssl x509 -in CAcert-example.com.pem -noout -text
```

you will see that all names and IPs are added to the SAN entries.

**Comment by sameo** [comment]
@tpepper And my interpretation of RFC2818 is that we should use a SANs DNSName lists as a replacement for the single entry CN. And I think this is what we do as `ciao-cli` will fail to generate a cert if --host is not provided.

**Comment by tpepper** [comment]
Aaaah I was looking for literal "subjectAltName" and the openssl -text does show it as X509v3 Subject Alternative Name so all is well!
