### ISSUE TITLE
block_data not cleaned up when cnci fails to start

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#851]
if the CNCI fails to start, the block_data object in the sqlite3 database still indicates that the volume is "in-use"

**Comment by rbradford** [comment]
I think I have a fix .. how do you test it?

**Comment by kaccardi** [comment]
@rbradford you can force the CNCI fail to launch by improperly configuring the network node. For example, delete the /etc/ceph directory on the network node, and the launcher on the node will be unable to access the cnci volume.

**Comment by tpepper** [comment]
I'm mucking in the same code with error paths and @rbradford's change here looks reasonable to me.
