### ISSUE TITLE
Attaching Volume to running container should fail

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#871]
It's not possible to attach a volume to a running container.  Volumes can only be attach to containers at creation time, i.e., there's no hotplugging of volumes to containers.  ciao-cli should therefore return an error.  Instead it attempts to attach the volume to a container.  It returns success but the volume is not attached.  It remains stuck in the attaching state for ever and cannot be deleted.   Zombie volume.

```
$ ciao-cli volume add -name zombie -size 1
Created new volume: 6817ab36-6b82-4088-8bd4-31be35c40ffb
$ ciao-cli instance add --workload ca957444-fa46-11e5-94f9-38607786d9ec
Created new instance: 7181b76b-5c60-40b6-8272-73b4197067aa
$ ciao-cli volume attach --instance 7181b76b-5c60-40b6-8272-73b4197067aa --volume 6817ab36-6b82-4088-8bd4-31be35c40ffb
Attached volume: 6817ab36-6b82-4088-8bd4-31be35c40ffb
$ sleep 60
$ ciao-cli volume show --volume 6817ab36-6b82-4088-8bd4-31be35c40ffb
	Name             [zombie]
	Size             [1 GB]
	UUID             [6817ab36-6b82-4088-8bd4-31be35c40ffb]
	Status           [attaching]
	Description      []
$ ciao-cli volume delete --volume 6817ab36-6b82-4088-8bd4-31be35c40ffb
F1125 14:27:50.350790   31705 main.go:403] ciao-cli FATAL: Expected HTTP response code [202 204] when accessing [DELETE https://singlevm:8776/v2/f452bbc7-5076-44d5-922c-3b9d2ce1503f/volumes/6817ab36-6b82-4088-8bd4-31be35c40ffb], but got 403 instead
Forbidden
```

This issue can also be reproduced by the unsubmitted TestAttachToRunningContainer BAT test.

**Comment by markdryan** [comment]
I have a patch for this but have not been able to fully test because of #875

**Comment by kaccardi** [comment]
@markdryan I reviewed the code in controller - it looks like this error path should cause the volume state to be reset to available. I also looked at the launcher code and it looks correct. @tpepper does the scheduler need to forward these errors explicitly? I don't see anything in the scheduler code to indicate that it does anything for these errors.
