### ISSUE TITLE
ansible changes for external IPs

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#881]
Modify the ansible scripts to include information in the ciao configuration yaml about which port the user would like to start the ciao http API on.

**Comment by albertomurillo** [comment]
Does this need a new keystone service/endpoint ?

**Comment by kaccardi** [comment]
@albertomurillo good question. It's not an openstack service - but it'd be nice to make it discoverable through the catalog. We'd have to call it something besides compute. I'm open to suggestions.

**Comment by kaccardi** [comment]
discussion with the UI team - they would like to be able to move to using the keystone catalog to discover services. I think we should call it the "ciao" service and add an endpoint for it.
