### ISSUE TITLE
ciao-cli: instance add does not validate -instances argument

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#889]
```
$ ciao-cli instance add -workload ${UUID} -instances="-1"                       
Created new instance: c554e9ca-d147-4c44-b9a7-9814667ce10b                      
$ ciao-cli instance add -workload ${UUID} -instances="-100"                     
Created new instance: eac343ad-0fae-4f27-ae7a-199c3d64751f
```

**Comment by tpepper** [comment]
It might make sense to extend the subCommand interface to include a validateArgs() to give a more clear expectation on input validation and a cohesive location for that.  Some validation appears to happen in the interface's run() and also in parseArgs() currently.

**Comment by markdryan** [comment]
@tpepper Absolutely agree.  ValidateArgs would allow us to detect errors earlier, i.e., before keystone validation.
