### ISSUE TITLE
ciao-controller: Transient database should go to tmpfs

### ISSUE THREAD

**Issue by obedmr** [01org/ciao#897]
Based on discussion that was started on #850 and on favor of performance, we're considering the use of tmpfs for transient datastore.

**Comment by tpepper** [comment]
To clarify slightly, different linux installations have different default behaviors with respect to available tmpfs mount points.  Depending on the set up of the machine running ciao-controller, /tmp may not be on tmpfs.  If we desire a tmpfs mount, we should make one explicitly, eg: /var/lib/ciao/tmp.

**Comment by kaccardi** [comment]
another option is to explore the use of an in memory DB for the transient DB, thus eliminating the need for tmpfs at all.

**Comment by rbradford** [comment]
As of #1337 controller uses a memory bbackend for the database.
