### ISSUE TITLE
ciao-deploy: Install dependencies

### ISSUE THREAD

**Issue by albertomurillo** [01org/ciao#899]
osprepare installs missing dependencies when the service starts but there is no way osprepare to yell when all the dependencies are installed and the service is ready to be used.

ciao_wait.yml include a task to check on the nodes that all the binaries have been installed.

It would be better to let ansible install the dependencies in the ciao nodes before starting the service. this way the services are ready to be used and any error installing the dependencies can be handled in the ansible playbooks.

**Comment by erick0z** [comment]
@albertomurillo the new CIAO Packages(ciao-controller, ciao-network, ciao-compute) provided by OBS now install the dependencies needed by Ciao except for Docker.

**Comment by albertomurillo** [comment]
ciao.spec file for fedora and ciao.dsc file for ubuntu now installs the required dependencies
Source code available at https://build.opensuse.org/package/show/home:clearlinux:preview:ciao/ciao

This issue can be closed now
