### ISSUE TITLE
Upgrade to docker 1.11.1

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#91]
Ciao is currently using a snapshot of the docker libraries from about 1 month ago.  It doesn't even build against docker/engine-api master.  We should update to docker 1.11.1.  This will involve:

1. Revendoring all the docker dependencies
2. Getting launcher to compile with the 1.11.1 client apis
3. Testing to make sure we haven't broken anything.
4. Updating our internal test clusters to use docker 1.11.1

**Comment by mcastelino** [comment]
Tested with latest docker without issues.
