### ISSUE TITLE
Single VM: SSH connectivity verification fails due to ssh key provisioning failure

### ISSUE THREAD

**Issue by mcastelino** [01org/ciao#913]
Looks like the change made in commit 
https://github.com/01org/ciao/commit/4922280d91f44ed7d75d6bed91ef774d1d9afbbb
the cloud-init is not being copied properly or not being used properly

**Comment by markdryan** [comment]
Actually it was 58d78ce526d6b4dfdd64f9ea4cd44f09b0de33e7 that broke this along with SingleVM as a whole.  Single VM was fixed in 4922280 but I missed the cloud-init workload used in verify.sh.
