### ISSUE TITLE
osprepare should not import glog

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#919]
Osprepare includes a logging abstraction that allows clients to specify how and where they would like osprepare's logs written.  It also includes an implementation of this abstraction based on glog.  The problem is that as soon as you import glog it adds the glog flags to your program.  So clients of osprepare autoamitcally get the glog flags added to their usage messages even if their implementation of osprepares logging abstraction doesn't use glog, which is irritating.

Osprepare's logging interface and abstraction need to be moved to a separate package.  So that they can be used by both osprepare and other packages, e.g, qemu.

**Comment by tpepper** [comment]
@bryteise was this something you were going to look at?

**Comment by bryteise** [comment]
Oh no I hadn't looked at that yet. I'll take a look at it though.

**Comment by bryteise** [comment]
@markdryan So are you looking for osprepare to shed its component specific logging for a generic toplevel (ciao-logger say) logging interface that osprepare would switch to and other components would start to use? Then osprepare would use that interface to add the current glog interface implementation?

**Comment by markdryan** [comment]
@bryteise Yes.  Pretty much.  The idea being that packages which function as libraries (osprepare, ssntp, qemu) wouldn't include glog at all.  They could then be used by programs which don't want or need to use glog.  Right now programs we write that use osprepare inherit the glog flags even if they never use glog which is undesirable.

We may need to put the abstract logging interface and the glog implementation in separate packages so osprepare doesn't import a package that imports glog.  This may mean that it's not possible for osprepare to provide a default glog implementation of its logs.

**Comment by bryteise** [comment]
@markdryan Okay. I agree there would be no default logging implementation outside of the null logger in the new implementation.
