### ISSUE TITLE
storage BAT tests do not work on release cluster

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#928]
TestDeleteBeforeDetached is failing.

Here's the log:

```
storage_bat TestDeleteBeforeDetached         300.00s    FAIL    
storage_bat TestAttachDetach                 N/A        NOT RUN 
storage_bat TestAttachToRunningContainer     N/A        NOT RUN 
storage_bat TestDoubleAttach                 N/A        NOT RUN 
storage_bat TestAttachToStoppedInstance      N/A        NOT RUN 


Logs for failed tests
---------------------
Logs for storage_bat.TestDeleteBeforeDetached
	storage_bat_test.go:403: Volume 7d4ccc8f-1970-4064-9223-b2dbc997a9cb status not available
	storage_bat_test.go:369: Failed to delete instance 11f85bb2-c230-4a56-ab39-b0198aeafb98 : failed to launch ciao-cli [instance delete -instance 11f85bb2-c230-4a56-ab39-b0198aeafb98] : context deadline exceeded
	storage_bat_test.go:374: Failed to delete volume 7d4ccc8f-1970-4064-9223-b2dbc997a9cb : failed to launch ciao-cli [volume delete --volume 7d4ccc8f-1970-4064-9223-b2dbc997a9cb] : context deadline exceeded
```

This test is running fine in Single VM so perhaps its a race condition of some kind.  Here's what the test is trying to do.

It detaches a volume from an instance and then tries to delete the volume straight away before the volume has transitioned back to available.  It looks like the attempt to delete the volume fails, which is expected, but afterwards the volume never again becomes available.  This is what the line

> storage_bat_test.go:403: Volume 7d4ccc8f-1970-4064-9223-b2dbc997a9cb status not available

means.  The test then tries to delete the instance but this attempt also fails.  I don't think ciao-cli is returning an error but the instance does not get deleted.

**Comment by markdryan** [comment]
Storage BAT tests are currently disabled on the release cluster due to this issue.

**Comment by markdryan** [comment]
Actually, the fact that the attempt to delete the instance fails is probably not relevant.  It's just failing as the context has timed out.  The question is, why does our volume never become available?

**Comment by kaccardi** [comment]
@markdryan I was able to successfully run the bat tests on the release cluster multiple times in a row without failure. So, I would guess either a race or some error condition that happened that wasn't handled right. Take a look at the controller logs when you do get a failure and see if you see anything odd.

**Comment by kaccardi** [comment]
closing - can reopen if errors reappear.
