### ISSUE TITLE
ciao-down start should block until the VM has booted

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#956]
Currently, if you do a ciao-down start on a stopped VM, the VM starts but has not usually finished booting by the time the start command returns.  Thus if you issue a ciao-down connect command straight away, it will probably fail as the ssh daemon is not yet running inside the guest.  It would be better if start blocked until the VM had booted.

**Comment by kaccardi** [comment]
i decided to bump up the priority on this one - I didn't realize how easy it was to trigger the issue.
