### ISSUE TITLE
tenantServerAction acts on instance without checking for tenant

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#98]
When an instance list is given to act on, tenantServerAction should check to see if an instance belongs to a tenant before allowing the action to proceed.

**Comment by leoswaldo** [comment]
I worked on this, I still need to make a test before sending pull request,  meanwhile you can see the commit  in my fork https://github.com/leoswaldo/ciao/commit/1a1caa5d81fe82edcf06ecca404138cdf1c446d1
