### ISSUE TITLE
ciao-down: connect sometimes doesn't work and provides no feedback

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#980]
sometimes when I do "ciao-down connect" after ciao-down status shows the VM is up, I am still unable to connect to the vm. If I wait long enough, I eventually can, but a lot of times not immediately. Unfortunately, connect doesn't tell me that it has failed, and unless I am smart enough to realize that I didn't get the usual start up message, I might think I was actually in my vm (yes, this happened to me) and start using singlevm on the host, thus getting hopelessly confused when my firewall blocks the cnci.

**Comment by markdryan** [comment]
This is probably related to #956, assuming that you're seeing this after doing a ciao-down start.  I need to get ciao-down start to block until the VM has booted.

**Comment by kaccardi** [comment]
yes, I see it after doing a ciao-down start.

**Comment by kaccardi** [comment]
I think this is a complete duplicate of that problem. I'll close it.

**Comment by kaccardi** [comment]
duplicate of #956
