### ISSUE TITLE
Installing ansible slows down Travis builds

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#996]
The "pip install ansible" step takes 42s (or so) on the travis builds for something that only changes very infrequently. It roughly takes 15% of our build time.

My proposal is to only install ansible and check the scripts only if the ansible files have changed.

**Comment by albertomurillo** [comment]
The ansible tests in travis only checks for errors in the playbook syntax. Since those test are not using the ciao code I agree with you on this.

It would be a time saver (not for me but still) :D
